<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\MagicLinks\Email\Discovery;


final class SendRequest
{
    /** The email address of the Member. */
    public string $emailAddress;
    /**
    * The URL that the end user clicks from the discovery Magic Link. This URL should be an endpoint in the
    * backend server that
    *   verifies the request by querying Stytch's discovery authenticate endpoint and continues the flow. If
    * this value is not passed, the default
    *   discovery redirect URL that you set in your Dashboard is used. If you have not set a default discovery
    * redirect URL, an error is returned.
     */
    public ?string $discoveryRedirectURL = null;
    /**
    * A base64url encoded SHA256 hash of a one time secret used to validate that the request starts and ends
    * on the same device.
     */
    public ?string $pkceCodeChallenge = null;
    /**
    * Use a custom template for discovery emails. By default, it will use your default email template. The
    * template must be from Stytch's
    * built-in customizations or a custom HTML email for Magic Links - Login.
     */
    public ?string $loginTemplateId = null;
    /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    * 
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), French (`"fr"`) and Brazilian
    * Portuguese (`"pt-br"`); if no value is provided, the copy defaults to English.
    * 
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
     */
    public ?string $locale = null;
    /**
    * The expiration time, in minutes, for an discovery magic link email. If not accepted within this time
    * frame, the email will need to be resent. Defaults to 60 (1 hour) with a minimum of 5 and a maximum of
    * 10080 (1 week).
     */
    public ?int $discoveryExpirationMinutes = null;

    public function __construct(
        string $emailAddress,
        ?string $discoveryRedirectURL = null,
        ?string $pkceCodeChallenge = null,
        ?string $loginTemplateId = null,
        ?string $locale = null,
        ?int $discoveryExpirationMinutes = null
    ) {
        $this->emailAddress = $emailAddress;
        $this->discoveryRedirectURL = $discoveryRedirectURL;
        $this->pkceCodeChallenge = $pkceCodeChallenge;
        $this->loginTemplateId = $loginTemplateId;
        $this->locale = $locale;
        $this->discoveryExpirationMinutes = $discoveryExpirationMinutes;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['email_address'],
            $data['discovery_redirect_url'] ?? null,
            $data['pkce_code_challenge'] ?? null,
            $data['login_template_id'] ?? null,
            $data['locale'] ?? null,
            $data['discovery_expiration_minutes'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'email_address' => $this->emailAddress,
            'discovery_redirect_url' => $this->discoveryRedirectURL,
            'pkce_code_challenge' => $this->pkceCodeChallenge,
            'login_template_id' => $this->loginTemplateId,
            'locale' => $this->locale,
            'discovery_expiration_minutes' => $this->discoveryExpirationMinutes,
        ];
    }
}