<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models;


final class DeviceAttributeDetails
{
    /** Whether this `ip_geo_country` has been seen before for this user. */
    public bool $isNew;
    /**
    * When this `ip_geo_country` was first seen for this user. Values conform to the RFC 3339 standard and are
    * expressed in UTC, e.g. `2021-12-29T12:33:09Z`.
     */
    public ?string $firstSeenAt = null;
    /**
    * When this `ip_geo_country` was last seen for this user. Values conform to the RFC 3339 standard and are
    * expressed in UTC, e.g. `2021-12-29T12:33:09Z`.
     */
    public ?string $lastSeenAt = null;

    public function __construct(
        bool $isNew,
        ?string $firstSeenAt = null,
        ?string $lastSeenAt = null
    ) {
        $this->isNew = $isNew;
        $this->firstSeenAt = $firstSeenAt;
        $this->lastSeenAt = $lastSeenAt;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['is_new'],
            $data['first_seen_at'] ?? null,
            $data['last_seen_at'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'is_new' => $this->isNew,
            'first_seen_at' => $this->firstSeenAt,
            'last_seen_at' => $this->lastSeenAt,
        ];
    }
}