<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models;

class ResetResponse
{
    public string $user_id;
    public User $user;
    public string $session_token;
    public string $session_jwt;
    public ?Session $session;
    public ?DeviceInfo $user_device;

    public function __construct(
        string $user_id,
        User $user,
        string $session_token,
        string $session_jwt,
        ?Session $session,
        ?DeviceInfo $user_device
    ) {
        $this->user_id = $user_id;
        $this->user = $user;
        $this->session_token = $session_token;
        $this->session_jwt = $session_jwt;
        $this->session = $session;
        $this->user_device = $user_device;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['user_id'],
            $data['user'],
            $data['session_token'],
            $data['session_jwt'],
            $data['session'] ?? null,
            $data['user_device'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'user_id' => $this->user_id,
            'user' => $this->user,
            'session_token' => $this->session_token,
            'session_jwt' => $this->session_jwt,
            'session' => $this->session,
            'user_device' => $this->user_device,
        ];
    }
}

