<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\IDP\OAuth;

class AuthorizeRequest
{
    public bool $consentGranted;
    public array $scopes;
    public string $clientId;
    public string $redirectUri;
    public string $responseType;
    public ?string $userId = null;
    public ?string $sessionToken = null;
    public ?string $sessionJwt = null;
    public ?string $prompt = null;
    public ?string $state = null;
    public ?string $nonce = null;
    public ?string $codeChallenge = null;

    public function __construct(
        bool $consentGranted,
        array $scopes,
        string $clientId,
        string $redirectUri,
        string $responseType,
        ?string $userId = null,
        ?string $sessionToken = null,
        ?string $sessionJwt = null,
        ?string $prompt = null,
        ?string $state = null,
        ?string $nonce = null,
        ?string $codeChallenge = null
    ) {
        $this->consentGranted = $consentGranted;
        $this->scopes = $scopes;
        $this->clientId = $clientId;
        $this->redirectUri = $redirectUri;
        $this->responseType = $responseType;
        $this->userId = $userId;
        $this->sessionToken = $sessionToken;
        $this->sessionJwt = $sessionJwt;
        $this->prompt = $prompt;
        $this->state = $state;
        $this->nonce = $nonce;
        $this->codeChallenge = $codeChallenge;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['consent_granted'],
            $data['scopes'],
            $data['client_id'],
            $data['redirect_uri'],
            $data['response_type'],
            $data['user_id'] ?? null,
            $data['session_token'] ?? null,
            $data['session_jwt'] ?? null,
            $data['prompt'] ?? null,
            $data['state'] ?? null,
            $data['nonce'] ?? null,
            $data['code_challenge'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'consent_granted' => $this->consentGranted,
            'scopes' => $this->scopes,
            'client_id' => $this->clientId,
            'redirect_uri' => $this->redirectUri,
            'response_type' => $this->responseType,
            'user_id' => $this->userId,
            'session_token' => $this->sessionToken,
            'session_jwt' => $this->sessionJwt,
            'prompt' => $this->prompt,
            'state' => $this->state,
            'nonce' => $this->nonce,
            'code_challenge' => $this->codeChallenge,
        ];
    }
}
