<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Fraud;

final class IPGeoProperties
{
    /** The city where the IP is located. */
    public string $city;
    /** The region where the IP is located. */
    public string $region;
    /** The country where the IP is located. */
    public string $country;

    public function __construct(
        string $city,
        string $region,
        string $country
    ) {
        $this->city = $city;
        $this->region = $region;
        $this->country = $country;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['city'],
            $data['region'],
            $data['country']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'city' => $this->city,
            'region' => $this->region,
            'country' => $this->country,
        ];
    }
}
