<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Fraud\VerdictReasons;

class OverrideRequest
{
    /**
    * The verdict reason that you wish to override. For a list of possible reasons to override, see
    * [Warning Flags (Verdict Reasons)](https://stytch.com/docs/docs/fraud/guides/device-fingerprinting/reference/warning-flags-verdict-reasons). You may not override the `RULE_MATCH` reason.
     */
    public string $verdictReason;
    /**
    * The action that you want to be returned for the specified verdict reason. The override action must be
    * one of `ALLOW`, `BLOCK`, or `CHALLENGE`.
     */
    public string $overrideAction;
    /** An optional description for the verdict reason override. */
    public ?string $overrideDescription = null;

    public function __construct(
        string $verdictReason,
        string $overrideAction,
        ?string $overrideDescription = null
    ) {
        $this->verdictReason = $verdictReason;
        $this->overrideAction = $overrideAction;
        $this->overrideDescription = $overrideDescription;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['verdict_reason'],
            $data['override_action'],
            $data['override_description'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'verdict_reason' => $this->verdictReason,
            'override_action' => $this->overrideAction,
            'override_description' => $this->overrideDescription,
        ];
    }
}
