<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Sessions;

final class AuthenticationFactor
{
    /**
    * The type of authentication factor. The possible values are: `email_otp`, `impersonated`, `imported`,
    *        `magic_link`, `oauth`, `otp`, `password`, `recovery_codes`, `sso`, `trusted_auth_token`, or
    * `totp`.
     */
    public string $type;
    /**
    * The method that was used to deliver the authentication factor. The possible values depend on the `type`:
    *
    *       `email_otp` – Only `email`.
    *
    *       `impersonated` – Only `impersonation`.
    *
    *       `imported` – Only `imported_auth0`.
    *
    *       `magic_link` – Only `email`.
    *
    *       `oauth` – The delivery method is determined by the specific OAuth provider used. The possible
    * values are `oauth_google`, `oauth_microsoft`, `oauth_hubspot`, `oauth_slack`, or `oauth_github`.
    *
    *         In addition, you may see an 'exchange' delivery method when a non-email-verifying OAuth factor
    * originally authenticated in one organization is exchanged for a factor in another organization.
    *         This can happen during authentication flows such as
    * [session exchange](https://stytch.com/docs/b2b/api/exchange-session).
    *         The non-email-verifying OAuth providers are Hubspot, Slack, and Github.
    *         Google is also considered non-email-verifying when the HD claim is empty.
    *         The possible exchange values are `oauth_exchange_google`, `oauth_exchange_hubspot`,
    * `oauth_exchange_slack`, or `oauth_exchange_github`.
    *
    *         The final possible value is `oauth_access_token_exchange`, if this factor came from an
    * [access token exchange flow](https://stytch.com/docs/b2b/api/connected-app-access-token-exchange).
    *
    *       `otp` –  Only `sms`.
    *
    *       `password` – Only `knowledge`.
    *
    *       `recovery_codes` – Only `recovery_code`.
    *
    *       `sso` – Either `sso_saml` or `sso_oidc`.
    *
    *       `trusted_auth_token` – Only `trusted_token_exchange`.
    *
    *       `totp` – Only `authenticator_app`.
     */
    public string $deliveryMethod;
    /** The timestamp when the factor was last authenticated. */
    public ?string $lastAuthenticatedAt = null;
    /** The timestamp when the factor was initially authenticated. */
    public ?string $createdAt = null;
    /** The timestamp when the factor was last updated. */
    public ?string $updatedAt = null;
    /** Information about the email factor, if one is present. */
    public ?EmailFactor $emailFactor = null;
    /** Information about the phone number factor, if one is present. */
    public ?PhoneNumberFactor $phoneNumberFactor = null;
    /** Information about the Google OAuth factor, if one is present. */
    public ?GoogleOAuthFactor $googleOAuthFactor = null;
    /** Information about the Microsoft OAuth factor, if one is present. */
    public ?MicrosoftOAuthFactor $microsoftOAuthFactor = null;
    public ?AppleOAuthFactor $appleOAuthFactor = null;
    public ?WebAuthnFactor $webauthnFactor = null;
    /** Information about the TOTP-backed Authenticator App factor, if one is present. */
    public ?AuthenticatorAppFactor $authenticatorAppFactor = null;
    /** Information about the Github OAuth factor, if one is present. */
    public ?GithubOAuthFactor $githubOAuthFactor = null;
    public ?RecoveryCodeFactor $recoveryCodeFactor = null;
    public ?FacebookOAuthFactor $facebookOAuthFactor = null;
    public ?CryptoWalletFactor $cryptoWalletFactor = null;
    public ?AmazonOAuthFactor $amazonOAuthFactor = null;
    public ?BitbucketOAuthFactor $bitbucketOAuthFactor = null;
    public ?CoinbaseOAuthFactor $coinbaseOAuthFactor = null;
    public ?DiscordOAuthFactor $discordOAuthFactor = null;
    public ?FigmaOAuthFactor $figmaOAuthFactor = null;
    public ?GitLabOAuthFactor $gitLabOAuthFactor = null;
    public ?InstagramOAuthFactor $instagramOAuthFactor = null;
    public ?LinkedInOAuthFactor $linkedInOAuthFactor = null;
    public ?ShopifyOAuthFactor $shopifyOAuthFactor = null;
    /** Information about the Slack OAuth factor, if one is present. */
    public ?SlackOAuthFactor $slackOAuthFactor = null;
    public ?SnapchatOAuthFactor $snapchatOAuthFactor = null;
    public ?SpotifyOAuthFactor $spotifyOAuthFactor = null;
    public ?SteamOAuthFactor $steamOAuthFactor = null;
    public ?TikTokOAuthFactor $tikTokOAuthFactor = null;
    public ?TwitchOAuthFactor $twitchOAuthFactor = null;
    public ?TwitterOAuthFactor $twitterOAuthFactor = null;
    public ?EmbeddableMagicLinkFactor $embeddableMagicLinkFactor = null;
    public ?BiometricFactor $biometricFactor = null;
    /** Information about the SAML SSO factor, if one is present. */
    public ?SAMLSSOFactor $samlSSOFactor = null;
    /** Information about the OIDC SSO factor, if one is present. */
    public ?OIDCSSOFactor $oidcSSOFactor = null;
    public ?SalesforceOAuthFactor $salesforceOAuthFactor = null;
    public ?YahooOAuthFactor $yahooOAuthFactor = null;
    /** Information about the Hubspot OAuth factor, if one is present. */
    public ?HubspotOAuthFactor $hubspotOAuthFactor = null;
    /** Information about the Slack OAuth Exchange factor, if one is present. */
    public ?SlackOAuthExchangeFactor $slackOAuthExchangeFactor = null;
    /** Information about the Hubspot OAuth Exchange factor, if one is present. */
    public ?HubspotOAuthExchangeFactor $hubspotOAuthExchangeFactor = null;
    /** Information about the Github OAuth Exchange factor, if one is present. */
    public ?GithubOAuthExchangeFactor $githubOAuthExchangeFactor = null;
    /** Information about the Google OAuth Exchange factor, if one is present. */
    public ?GoogleOAuthExchangeFactor $googleOAuthExchangeFactor = null;
    /** Information about the impersonated factor, if one is present. */
    public ?ImpersonatedFactor $impersonatedFactor = null;
    /** Information about the access token exchange factor, if one is present. */
    public ?OAuthAccessTokenExchangeFactor $oauthAccessTokenExchangeFactor = null;
    /** Information about the trusted auth token factor, if one is present. */
    public ?TrustedAuthTokenFactor $trustedAuthTokenFactor = null;

    public function __construct(
        string $type,
        string $deliveryMethod,
        ?string $lastAuthenticatedAt = null,
        ?string $createdAt = null,
        ?string $updatedAt = null,
        ?EmailFactor $emailFactor = null,
        ?PhoneNumberFactor $phoneNumberFactor = null,
        ?GoogleOAuthFactor $googleOAuthFactor = null,
        ?MicrosoftOAuthFactor $microsoftOAuthFactor = null,
        ?AppleOAuthFactor $appleOAuthFactor = null,
        ?WebAuthnFactor $webauthnFactor = null,
        ?AuthenticatorAppFactor $authenticatorAppFactor = null,
        ?GithubOAuthFactor $githubOAuthFactor = null,
        ?RecoveryCodeFactor $recoveryCodeFactor = null,
        ?FacebookOAuthFactor $facebookOAuthFactor = null,
        ?CryptoWalletFactor $cryptoWalletFactor = null,
        ?AmazonOAuthFactor $amazonOAuthFactor = null,
        ?BitbucketOAuthFactor $bitbucketOAuthFactor = null,
        ?CoinbaseOAuthFactor $coinbaseOAuthFactor = null,
        ?DiscordOAuthFactor $discordOAuthFactor = null,
        ?FigmaOAuthFactor $figmaOAuthFactor = null,
        ?GitLabOAuthFactor $gitLabOAuthFactor = null,
        ?InstagramOAuthFactor $instagramOAuthFactor = null,
        ?LinkedInOAuthFactor $linkedInOAuthFactor = null,
        ?ShopifyOAuthFactor $shopifyOAuthFactor = null,
        ?SlackOAuthFactor $slackOAuthFactor = null,
        ?SnapchatOAuthFactor $snapchatOAuthFactor = null,
        ?SpotifyOAuthFactor $spotifyOAuthFactor = null,
        ?SteamOAuthFactor $steamOAuthFactor = null,
        ?TikTokOAuthFactor $tikTokOAuthFactor = null,
        ?TwitchOAuthFactor $twitchOAuthFactor = null,
        ?TwitterOAuthFactor $twitterOAuthFactor = null,
        ?EmbeddableMagicLinkFactor $embeddableMagicLinkFactor = null,
        ?BiometricFactor $biometricFactor = null,
        ?SAMLSSOFactor $samlSSOFactor = null,
        ?OIDCSSOFactor $oidcSSOFactor = null,
        ?SalesforceOAuthFactor $salesforceOAuthFactor = null,
        ?YahooOAuthFactor $yahooOAuthFactor = null,
        ?HubspotOAuthFactor $hubspotOAuthFactor = null,
        ?SlackOAuthExchangeFactor $slackOAuthExchangeFactor = null,
        ?HubspotOAuthExchangeFactor $hubspotOAuthExchangeFactor = null,
        ?GithubOAuthExchangeFactor $githubOAuthExchangeFactor = null,
        ?GoogleOAuthExchangeFactor $googleOAuthExchangeFactor = null,
        ?ImpersonatedFactor $impersonatedFactor = null,
        ?OAuthAccessTokenExchangeFactor $oauthAccessTokenExchangeFactor = null,
        ?TrustedAuthTokenFactor $trustedAuthTokenFactor = null
    ) {
        $this->type = $type;
        $this->deliveryMethod = $deliveryMethod;
        $this->lastAuthenticatedAt = $lastAuthenticatedAt;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->emailFactor = $emailFactor;
        $this->phoneNumberFactor = $phoneNumberFactor;
        $this->googleOAuthFactor = $googleOAuthFactor;
        $this->microsoftOAuthFactor = $microsoftOAuthFactor;
        $this->appleOAuthFactor = $appleOAuthFactor;
        $this->webauthnFactor = $webauthnFactor;
        $this->authenticatorAppFactor = $authenticatorAppFactor;
        $this->githubOAuthFactor = $githubOAuthFactor;
        $this->recoveryCodeFactor = $recoveryCodeFactor;
        $this->facebookOAuthFactor = $facebookOAuthFactor;
        $this->cryptoWalletFactor = $cryptoWalletFactor;
        $this->amazonOAuthFactor = $amazonOAuthFactor;
        $this->bitbucketOAuthFactor = $bitbucketOAuthFactor;
        $this->coinbaseOAuthFactor = $coinbaseOAuthFactor;
        $this->discordOAuthFactor = $discordOAuthFactor;
        $this->figmaOAuthFactor = $figmaOAuthFactor;
        $this->gitLabOAuthFactor = $gitLabOAuthFactor;
        $this->instagramOAuthFactor = $instagramOAuthFactor;
        $this->linkedInOAuthFactor = $linkedInOAuthFactor;
        $this->shopifyOAuthFactor = $shopifyOAuthFactor;
        $this->slackOAuthFactor = $slackOAuthFactor;
        $this->snapchatOAuthFactor = $snapchatOAuthFactor;
        $this->spotifyOAuthFactor = $spotifyOAuthFactor;
        $this->steamOAuthFactor = $steamOAuthFactor;
        $this->tikTokOAuthFactor = $tikTokOAuthFactor;
        $this->twitchOAuthFactor = $twitchOAuthFactor;
        $this->twitterOAuthFactor = $twitterOAuthFactor;
        $this->embeddableMagicLinkFactor = $embeddableMagicLinkFactor;
        $this->biometricFactor = $biometricFactor;
        $this->samlSSOFactor = $samlSSOFactor;
        $this->oidcSSOFactor = $oidcSSOFactor;
        $this->salesforceOAuthFactor = $salesforceOAuthFactor;
        $this->yahooOAuthFactor = $yahooOAuthFactor;
        $this->hubspotOAuthFactor = $hubspotOAuthFactor;
        $this->slackOAuthExchangeFactor = $slackOAuthExchangeFactor;
        $this->hubspotOAuthExchangeFactor = $hubspotOAuthExchangeFactor;
        $this->githubOAuthExchangeFactor = $githubOAuthExchangeFactor;
        $this->googleOAuthExchangeFactor = $googleOAuthExchangeFactor;
        $this->impersonatedFactor = $impersonatedFactor;
        $this->oauthAccessTokenExchangeFactor = $oauthAccessTokenExchangeFactor;
        $this->trustedAuthTokenFactor = $trustedAuthTokenFactor;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['type'],
            $data['delivery_method'],
            $data['last_authenticated_at'] ?? null,
            $data['created_at'] ?? null,
            $data['updated_at'] ?? null,
            isset($data['email_factor']) && $data['email_factor'] !== null ? EmailFactor::fromArray($data['email_factor']) : null,
            isset($data['phone_number_factor']) && $data['phone_number_factor'] !== null ? PhoneNumberFactor::fromArray($data['phone_number_factor']) : null,
            isset($data['google_oauth_factor']) && $data['google_oauth_factor'] !== null ? GoogleOAuthFactor::fromArray($data['google_oauth_factor']) : null,
            isset($data['microsoft_oauth_factor']) && $data['microsoft_oauth_factor'] !== null ? MicrosoftOAuthFactor::fromArray($data['microsoft_oauth_factor']) : null,
            isset($data['apple_oauth_factor']) && $data['apple_oauth_factor'] !== null ? AppleOAuthFactor::fromArray($data['apple_oauth_factor']) : null,
            isset($data['webauthn_factor']) && $data['webauthn_factor'] !== null ? WebAuthnFactor::fromArray($data['webauthn_factor']) : null,
            isset($data['authenticator_app_factor']) && $data['authenticator_app_factor'] !== null ? AuthenticatorAppFactor::fromArray($data['authenticator_app_factor']) : null,
            isset($data['github_oauth_factor']) && $data['github_oauth_factor'] !== null ? GithubOAuthFactor::fromArray($data['github_oauth_factor']) : null,
            isset($data['recovery_code_factor']) && $data['recovery_code_factor'] !== null ? RecoveryCodeFactor::fromArray($data['recovery_code_factor']) : null,
            isset($data['facebook_oauth_factor']) && $data['facebook_oauth_factor'] !== null ? FacebookOAuthFactor::fromArray($data['facebook_oauth_factor']) : null,
            isset($data['crypto_wallet_factor']) && $data['crypto_wallet_factor'] !== null ? CryptoWalletFactor::fromArray($data['crypto_wallet_factor']) : null,
            isset($data['amazon_oauth_factor']) && $data['amazon_oauth_factor'] !== null ? AmazonOAuthFactor::fromArray($data['amazon_oauth_factor']) : null,
            isset($data['bitbucket_oauth_factor']) && $data['bitbucket_oauth_factor'] !== null ? BitbucketOAuthFactor::fromArray($data['bitbucket_oauth_factor']) : null,
            isset($data['coinbase_oauth_factor']) && $data['coinbase_oauth_factor'] !== null ? CoinbaseOAuthFactor::fromArray($data['coinbase_oauth_factor']) : null,
            isset($data['discord_oauth_factor']) && $data['discord_oauth_factor'] !== null ? DiscordOAuthFactor::fromArray($data['discord_oauth_factor']) : null,
            isset($data['figma_oauth_factor']) && $data['figma_oauth_factor'] !== null ? FigmaOAuthFactor::fromArray($data['figma_oauth_factor']) : null,
            isset($data['git_lab_oauth_factor']) && $data['git_lab_oauth_factor'] !== null ? GitLabOAuthFactor::fromArray($data['git_lab_oauth_factor']) : null,
            isset($data['instagram_oauth_factor']) && $data['instagram_oauth_factor'] !== null ? InstagramOAuthFactor::fromArray($data['instagram_oauth_factor']) : null,
            isset($data['linked_in_oauth_factor']) && $data['linked_in_oauth_factor'] !== null ? LinkedInOAuthFactor::fromArray($data['linked_in_oauth_factor']) : null,
            isset($data['shopify_oauth_factor']) && $data['shopify_oauth_factor'] !== null ? ShopifyOAuthFactor::fromArray($data['shopify_oauth_factor']) : null,
            isset($data['slack_oauth_factor']) && $data['slack_oauth_factor'] !== null ? SlackOAuthFactor::fromArray($data['slack_oauth_factor']) : null,
            isset($data['snapchat_oauth_factor']) && $data['snapchat_oauth_factor'] !== null ? SnapchatOAuthFactor::fromArray($data['snapchat_oauth_factor']) : null,
            isset($data['spotify_oauth_factor']) && $data['spotify_oauth_factor'] !== null ? SpotifyOAuthFactor::fromArray($data['spotify_oauth_factor']) : null,
            isset($data['steam_oauth_factor']) && $data['steam_oauth_factor'] !== null ? SteamOAuthFactor::fromArray($data['steam_oauth_factor']) : null,
            isset($data['tik_tok_oauth_factor']) && $data['tik_tok_oauth_factor'] !== null ? TikTokOAuthFactor::fromArray($data['tik_tok_oauth_factor']) : null,
            isset($data['twitch_oauth_factor']) && $data['twitch_oauth_factor'] !== null ? TwitchOAuthFactor::fromArray($data['twitch_oauth_factor']) : null,
            isset($data['twitter_oauth_factor']) && $data['twitter_oauth_factor'] !== null ? TwitterOAuthFactor::fromArray($data['twitter_oauth_factor']) : null,
            isset($data['embeddable_magic_link_factor']) && $data['embeddable_magic_link_factor'] !== null ? EmbeddableMagicLinkFactor::fromArray($data['embeddable_magic_link_factor']) : null,
            isset($data['biometric_factor']) && $data['biometric_factor'] !== null ? BiometricFactor::fromArray($data['biometric_factor']) : null,
            isset($data['saml_sso_factor']) && $data['saml_sso_factor'] !== null ? SAMLSSOFactor::fromArray($data['saml_sso_factor']) : null,
            isset($data['oidc_sso_factor']) && $data['oidc_sso_factor'] !== null ? OIDCSSOFactor::fromArray($data['oidc_sso_factor']) : null,
            isset($data['salesforce_oauth_factor']) && $data['salesforce_oauth_factor'] !== null ? SalesforceOAuthFactor::fromArray($data['salesforce_oauth_factor']) : null,
            isset($data['yahoo_oauth_factor']) && $data['yahoo_oauth_factor'] !== null ? YahooOAuthFactor::fromArray($data['yahoo_oauth_factor']) : null,
            isset($data['hubspot_oauth_factor']) && $data['hubspot_oauth_factor'] !== null ? HubspotOAuthFactor::fromArray($data['hubspot_oauth_factor']) : null,
            isset($data['slack_oauth_exchange_factor']) && $data['slack_oauth_exchange_factor'] !== null ? SlackOAuthExchangeFactor::fromArray($data['slack_oauth_exchange_factor']) : null,
            isset($data['hubspot_oauth_exchange_factor']) && $data['hubspot_oauth_exchange_factor'] !== null ? HubspotOAuthExchangeFactor::fromArray($data['hubspot_oauth_exchange_factor']) : null,
            isset($data['github_oauth_exchange_factor']) && $data['github_oauth_exchange_factor'] !== null ? GithubOAuthExchangeFactor::fromArray($data['github_oauth_exchange_factor']) : null,
            isset($data['google_oauth_exchange_factor']) && $data['google_oauth_exchange_factor'] !== null ? GoogleOAuthExchangeFactor::fromArray($data['google_oauth_exchange_factor']) : null,
            isset($data['impersonated_factor']) && $data['impersonated_factor'] !== null ? ImpersonatedFactor::fromArray($data['impersonated_factor']) : null,
            isset($data['oauth_access_token_exchange_factor']) && $data['oauth_access_token_exchange_factor'] !== null ? OAuthAccessTokenExchangeFactor::fromArray($data['oauth_access_token_exchange_factor']) : null,
            isset($data['trusted_auth_token_factor']) && $data['trusted_auth_token_factor'] !== null ? TrustedAuthTokenFactor::fromArray($data['trusted_auth_token_factor']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'type' => $this->type,
            'delivery_method' => $this->deliveryMethod,
            'last_authenticated_at' => $this->lastAuthenticatedAt,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
            'email_factor' => $this->emailFactor,
            'phone_number_factor' => $this->phoneNumberFactor,
            'google_oauth_factor' => $this->googleOAuthFactor,
            'microsoft_oauth_factor' => $this->microsoftOAuthFactor,
            'apple_oauth_factor' => $this->appleOAuthFactor,
            'webauthn_factor' => $this->webauthnFactor,
            'authenticator_app_factor' => $this->authenticatorAppFactor,
            'github_oauth_factor' => $this->githubOAuthFactor,
            'recovery_code_factor' => $this->recoveryCodeFactor,
            'facebook_oauth_factor' => $this->facebookOAuthFactor,
            'crypto_wallet_factor' => $this->cryptoWalletFactor,
            'amazon_oauth_factor' => $this->amazonOAuthFactor,
            'bitbucket_oauth_factor' => $this->bitbucketOAuthFactor,
            'coinbase_oauth_factor' => $this->coinbaseOAuthFactor,
            'discord_oauth_factor' => $this->discordOAuthFactor,
            'figma_oauth_factor' => $this->figmaOAuthFactor,
            'git_lab_oauth_factor' => $this->gitLabOAuthFactor,
            'instagram_oauth_factor' => $this->instagramOAuthFactor,
            'linked_in_oauth_factor' => $this->linkedInOAuthFactor,
            'shopify_oauth_factor' => $this->shopifyOAuthFactor,
            'slack_oauth_factor' => $this->slackOAuthFactor,
            'snapchat_oauth_factor' => $this->snapchatOAuthFactor,
            'spotify_oauth_factor' => $this->spotifyOAuthFactor,
            'steam_oauth_factor' => $this->steamOAuthFactor,
            'tik_tok_oauth_factor' => $this->tikTokOAuthFactor,
            'twitch_oauth_factor' => $this->twitchOAuthFactor,
            'twitter_oauth_factor' => $this->twitterOAuthFactor,
            'embeddable_magic_link_factor' => $this->embeddableMagicLinkFactor,
            'biometric_factor' => $this->biometricFactor,
            'saml_sso_factor' => $this->samlSSOFactor,
            'oidc_sso_factor' => $this->oidcSSOFactor,
            'salesforce_oauth_factor' => $this->salesforceOAuthFactor,
            'yahoo_oauth_factor' => $this->yahooOAuthFactor,
            'hubspot_oauth_factor' => $this->hubspotOAuthFactor,
            'slack_oauth_exchange_factor' => $this->slackOAuthExchangeFactor,
            'hubspot_oauth_exchange_factor' => $this->hubspotOAuthExchangeFactor,
            'github_oauth_exchange_factor' => $this->githubOAuthExchangeFactor,
            'google_oauth_exchange_factor' => $this->googleOAuthExchangeFactor,
            'impersonated_factor' => $this->impersonatedFactor,
            'oauth_access_token_exchange_factor' => $this->oauthAccessTokenExchangeFactor,
            'trusted_auth_token_factor' => $this->trustedAuthTokenFactor,
        ];
    }
}
