<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Sessions;

final class CryptoWalletFactor
{
    public string $cryptoWalletId;
    public string $cryptoWalletAddress;
    public string $cryptoWalletType;

    public function __construct(
        string $cryptoWalletId,
        string $cryptoWalletAddress,
        string $cryptoWalletType
    ) {
        $this->cryptoWalletId = $cryptoWalletId;
        $this->cryptoWalletAddress = $cryptoWalletAddress;
        $this->cryptoWalletType = $cryptoWalletType;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['crypto_wallet_id'],
            $data['crypto_wallet_address'],
            $data['crypto_wallet_type']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'crypto_wallet_id' => $this->cryptoWalletId,
            'crypto_wallet_address' => $this->cryptoWalletAddress,
            'crypto_wallet_type' => $this->cryptoWalletType,
        ];
    }
}
