<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Sessions;


final class JWK
{
    public string $kty;
    public string $use;
    public array $keyOps;
    public string $alg;
    public string $kid;
    public array $x5C;
    public string $x5TS256;
    public string $n;
    public string $e;

    public function __construct(
        string $kty,
        string $use,
        array $keyOps,
        string $alg,
        string $kid,
        array $x5C,
        string $x5TS256,
        string $n,
        string $e
    ) {
        $this->kty = $kty;
        $this->use = $use;
        $this->keyOps = $keyOps;
        $this->alg = $alg;
        $this->kid = $kid;
        $this->x5C = $x5C;
        $this->x5TS256 = $x5TS256;
        $this->n = $n;
        $this->e = $e;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['kty'],
            $data['use'],
            $data['key_ops'],
            $data['alg'],
            $data['kid'],
            $data['x5c'],
            $data['x5tS256'],
            $data['n'],
            $data['e']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'kty' => $this->kty,
            'use' => $this->use,
            'key_ops' => $this->keyOps,
            'alg' => $this->alg,
            'kid' => $this->kid,
            'x5c' => $this->x5C,
            'x5tS256' => $this->x5TS256,
            'n' => $this->n,
            'e' => $this->e,
        ];
    }
}