<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Sessions;

final class RecoveryCodeFactor
{
    public string $totpRecoveryCodeId;

    public function __construct(
        string $totpRecoveryCodeId
    ) {
        $this->totpRecoveryCodeId = $totpRecoveryCodeId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['totp_recovery_code_id']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'totp_recovery_code_id' => $this->totpRecoveryCodeId,
        ];
    }
}
