<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Sessions;

final class TrustedAuthTokenFactor
{
    /** The ID of the trusted auth token. */
    public string $tokenId;

    public function __construct(
        string $tokenId
    ) {
        $this->tokenId = $tokenId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['token_id']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'token_id' => $this->tokenId,
        ];
    }
}
