<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Sessions;

class TwitchOAuthFactor
{
    public string $id;
    public string $providerSubject;
    public ?string $emailId = null;

    public function __construct(
        string $id,
        string $providerSubject,
        ?string $emailId = null
    ) {
        $this->id = $id;
        $this->providerSubject = $providerSubject;
        $this->emailId = $emailId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['id'],
            $data['provider_subject'],
            $data['email_id'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'provider_subject' => $this->providerSubject,
            'email_id' => $this->emailId,
        ];
    }
}
