<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Sessions;


final class AuthenticateResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /** The [Session object](https://stytch.com/docs/b2b/api/session-object). */
    public MemberSession $memberSession;
    /** A secret token for a given Stytch Session. */
    public string $sessionToken;
    /** The JSON Web Token (JWT) for a given Stytch Session. */
    public string $sessionJwt;
    /** The [Member object](https://stytch.com/docs/b2b/api/member-object) */
    public \Stytch\B2B\Models\Organizations\Member $member;
    /** The [Organization object](https://stytch.com/docs/b2b/api/organization-object). */
    public \Stytch\B2B\Models\Organizations\Organization $organization;
    /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
     */
    public int $statusCode;
    /**
    * If an `authorization_check` is provided in the request and the check succeeds, this field will return
    *   information about why the Member was granted permission.
     */
    public ?AuthorizationVerdict $verdict = null;

    public function __construct(
        string $requestId,
        MemberSession $memberSession,
        string $sessionToken,
        string $sessionJwt,
        \Stytch\B2B\Models\Organizations\Member $member,
        \Stytch\B2B\Models\Organizations\Organization $organization,
        int $statusCode,
        ?AuthorizationVerdict $verdict = null
    ) {
        $this->requestId = $requestId;
        $this->memberSession = $memberSession;
        $this->sessionToken = $sessionToken;
        $this->sessionJwt = $sessionJwt;
        $this->member = $member;
        $this->organization = $organization;
        $this->statusCode = $statusCode;
        $this->verdict = $verdict;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            MemberSession::fromArray($data['member_session']),
            $data['session_token'],
            $data['session_jwt'],
            \Stytch\B2B\Models\Organizations\Member::fromArray($data['member']),
            \Stytch\B2B\Models\Organizations\Organization::fromArray($data['organization']),
            $data['status_code'],
            $data['verdict'] !== null ? AuthorizationVerdict::fromArray($data['verdict']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'member_session' => $this->memberSession,
            'session_token' => $this->sessionToken,
            'session_jwt' => $this->sessionJwt,
            'member' => $this->member,
            'organization' => $this->organization,
            'status_code' => $this->statusCode,
            'verdict' => $this->verdict,
        ];
    }
}