<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Sessions;

class MigrateResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /** Globally unique UUID that identifies a specific Member. */
    public string $memberId;
    /** A secret token for a given Stytch Session. */
    public string $sessionToken;
    /** The JSON Web Token (JWT) for a given Stytch Session. */
    public string $sessionJwt;
    /** The [Member object](https://stytch.com/docs/b2b/api/member-object) */
    public \Stytch\B2B\Models\Organizations\Member $member;
    /** The [Organization object](https://stytch.com/docs/b2b/api/organization-object). */
    public \Stytch\B2B\Models\Organizations\Organization $organization;
    public int $statusCode;
    /** The [Session object](https://stytch.com/docs/b2b/api/session-object). */
    public ?MemberSession $memberSession = null;

    public function __construct(
        string $requestId,
        string $memberId,
        string $sessionToken,
        string $sessionJwt,
        \Stytch\B2B\Models\Organizations\Member $member,
        \Stytch\B2B\Models\Organizations\Organization $organization,
        int $statusCode,
        ?MemberSession $memberSession = null
    ) {
        $this->requestId = $requestId;
        $this->memberId = $memberId;
        $this->sessionToken = $sessionToken;
        $this->sessionJwt = $sessionJwt;
        $this->member = $member;
        $this->organization = $organization;
        $this->statusCode = $statusCode;
        $this->memberSession = $memberSession;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['member_id'],
            $data['session_token'],
            $data['session_jwt'],
            \Stytch\B2B\Models\Organizations\Member::fromArray($data['member']),
            \Stytch\B2B\Models\Organizations\Organization::fromArray($data['organization']),
            $data['status_code'],
            $data['member_session'] !== null ? MemberSession::fromArray($data['member_session']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'member_id' => $this->memberId,
            'session_token' => $this->sessionToken,
            'session_jwt' => $this->sessionJwt,
            'member' => $this->member,
            'organization' => $this->organization,
            'status_code' => $this->statusCode,
            'member_session' => $this->memberSession,
        ];
    }
}
