<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\IDP;

final class ScopeResult
{
    public string $scope;
    public string $description;
    public bool $isGrantable;

    public function __construct(
        string $scope,
        string $description,
        bool $isGrantable
    ) {
        $this->scope = $scope;
        $this->description = $description;
        $this->isGrantable = $isGrantable;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['scope'],
            $data['description'],
            $data['is_grantable']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'scope' => $this->scope,
            'description' => $this->description,
            'is_grantable' => $this->isGrantable,
        ];
    }
}
