<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations\Members;

final class DeleteExternalIdResponse
{
    public string $requestId;
    public string $memberId;
    public \Stytch\B2B\Models\Organizations\Member $member;
    public \Stytch\B2B\Models\Organizations\Organization $organization;
    public int $statusCode;

    public function __construct(
        string $requestId,
        string $memberId,
        \Stytch\B2B\Models\Organizations\Member $member,
        \Stytch\B2B\Models\Organizations\Organization $organization,
        int $statusCode
    ) {
        $this->requestId = $requestId;
        $this->memberId = $memberId;
        $this->member = $member;
        $this->organization = $organization;
        $this->statusCode = $statusCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['member_id'],
            \Stytch\B2B\Models\Organizations\Member::fromArray($data['member']),
            \Stytch\B2B\Models\Organizations\Organization::fromArray($data['organization']),
            $data['status_code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'member_id' => $this->memberId,
            'member' => $this->member,
            'organization' => $this->organization,
            'status_code' => $this->statusCode,
        ];
    }
}
