<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Passwords;


final class StrengthCheckRequest
{
    /**
    * The password to authenticate, reset, or set for the first time. Any UTF8 character is allowed, e.g.
    * spaces, emojis, non-English characters, etc.
     */
    public string $password;
    /** The email address of the Member. */
    public ?string $emailAddress = null;

    public function __construct(
        string $password,
        ?string $emailAddress = null
    ) {
        $this->password = $password;
        $this->emailAddress = $emailAddress;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['password'],
            $data['email_address'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'password' => $this->password,
            'email_address' => $this->emailAddress,
        ];
    }
}