<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\RBAC;

final class PolicyScopePermission
{
    /**
    * A unique identifier of the RBAC Resource, provided by the developer and intended to be human-readable.
    *
    *   A `resource_id` is not allowed to start with `stytch`, which is a special prefix used for Stytch
    * default Resources with reserved `resource_id`s.
     */
    public string $resourceId;
    /**
    * A list of permitted actions the Scope is required to take with the provided Resource. You can use `*` as
    * a wildcard to require a Scope permission to use all possible actions related to the Resource.
     */
    public array $actions;

    public function __construct(
        string $resourceId,
        array $actions
    ) {
        $this->resourceId = $resourceId;
        $this->actions = $actions;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['resource_id'],
            $data['actions']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'resource_id' => $this->resourceId,
            'actions' => $this->actions,
        ];
    }
}
