<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\SCIM;


final class Address
{
    public string $formatted;
    public string $streetAddress;
    public string $locality;
    public string $region;
    public string $postalCode;
    public string $country;
    public string $type;
    public bool $primary;

    public function __construct(
        string $formatted,
        string $streetAddress,
        string $locality,
        string $region,
        string $postalCode,
        string $country,
        string $type,
        bool $primary
    ) {
        $this->formatted = $formatted;
        $this->streetAddress = $streetAddress;
        $this->locality = $locality;
        $this->region = $region;
        $this->postalCode = $postalCode;
        $this->country = $country;
        $this->type = $type;
        $this->primary = $primary;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['formatted'],
            $data['street_address'],
            $data['locality'],
            $data['region'],
            $data['postal_code'],
            $data['country'],
            $data['type'],
            $data['primary']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'formatted' => $this->formatted,
            'street_address' => $this->streetAddress,
            'locality' => $this->locality,
            'region' => $this->region,
            'postal_code' => $this->postalCode,
            'country' => $this->country,
            'type' => $this->type,
            'primary' => $this->primary,
        ];
    }
}