<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\SCIM;


final class SCIMConnectionWithNextToken
{
    public string $organizationId;
    public string $connectionId;
    public string $status;
    public string $displayName;
    public string $baseURL;
    public string $identityProvider;
    public string $bearerTokenLastFour;
    public string $nextBearerToken;
    public array $scimGroupImplicitRoleAssignments;
    public ?string $bearerTokenExpiresAt = null;
    public ?string $nextBearerTokenExpiresAt = null;

    public function __construct(
        string $organizationId,
        string $connectionId,
        string $status,
        string $displayName,
        string $baseURL,
        string $identityProvider,
        string $bearerTokenLastFour,
        string $nextBearerToken,
        array $scimGroupImplicitRoleAssignments,
        ?string $bearerTokenExpiresAt = null,
        ?string $nextBearerTokenExpiresAt = null
    ) {
        $this->organizationId = $organizationId;
        $this->connectionId = $connectionId;
        $this->status = $status;
        $this->displayName = $displayName;
        $this->baseURL = $baseURL;
        $this->identityProvider = $identityProvider;
        $this->bearerTokenLastFour = $bearerTokenLastFour;
        $this->nextBearerToken = $nextBearerToken;
        $this->scimGroupImplicitRoleAssignments = $scimGroupImplicitRoleAssignments;
        $this->bearerTokenExpiresAt = $bearerTokenExpiresAt;
        $this->nextBearerTokenExpiresAt = $nextBearerTokenExpiresAt;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['organization_id'],
            $data['connection_id'],
            $data['status'],
            $data['display_name'],
            $data['base_url'],
            $data['identity_provider'],
            $data['bearer_token_last_four'],
            $data['next_bearer_token'],
            isset($data['scim_group_implicit_role_assignments']) ? array_map(fn($item) => SCIMGroupImplicitRoleAssignments::fromArray($item), $data['scim_group_implicit_role_assignments']) : [],
            $data['bearer_token_expires_at'] ?? null,
            $data['next_bearer_token_expires_at'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'connection_id' => $this->connectionId,
            'status' => $this->status,
            'display_name' => $this->displayName,
            'base_url' => $this->baseURL,
            'identity_provider' => $this->identityProvider,
            'bearer_token_last_four' => $this->bearerTokenLastFour,
            'next_bearer_token' => $this->nextBearerToken,
            'scim_group_implicit_role_assignments' => $this->scimGroupImplicitRoleAssignments,
            'bearer_token_expires_at' => $this->bearerTokenExpiresAt,
            'next_bearer_token_expires_at' => $this->nextBearerTokenExpiresAt,
        ];
    }
}