<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\SCIM;

class SCIMGroup
{
    /**
    * Stytch-issued, globally unique UUID that identifies a specific SCIM Group. The entity `id` in the SCIM
    * specification is issued by the Service Provider (SP) and returned to the Identity Provider (IdP) to
    * store and use for uniquely identify and updating the Group moving forward.
     */
    public string $groupId;
    /** The displayName of the SCIM group, sent from the Identity Provider (IdP). */
    public string $groupName;
    /**
    * Globally unique UUID that identifies a specific Organization. The organization_id is critical to perform
    * operations on an Organization, so be sure to preserve this value.
     */
    public string $organizationId;
    /** The ID of the SCIM connection. */
    public string $connectionId;

    public function __construct(
        string $groupId,
        string $groupName,
        string $organizationId,
        string $connectionId
    ) {
        $this->groupId = $groupId;
        $this->groupName = $groupName;
        $this->organizationId = $organizationId;
        $this->connectionId = $connectionId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['group_id'],
            $data['group_name'],
            $data['organization_id'],
            $data['connection_id']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'group_id' => $this->groupId,
            'group_name' => $this->groupName,
            'organization_id' => $this->organizationId,
            'connection_id' => $this->connectionId,
        ];
    }
}
