<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\MagicLinks\Email;

final class InviteRequest
{
    /** The email address of the User to send the invite Magic Link to. */
    public string $email;
    /**
    * Use a custom template for invite emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Invite.
     */
    public ?string $inviteTemplateId = null;
    /**
    * Provided attributes to help with fraud detection. These values are pulled and passed into Stytch
    * endpoints by your application.
     */
    public ?\Stytch\Consumer\Models\Attributes $attributes = null;
    /** The name of the user. Each field in the name object is optional. */
    public ?\Stytch\Consumer\Models\Users\Name $name = null;
    /**
    * The URL the end user clicks from the Email Magic Link. This should be a URL that your app receives and
    * parses and subsequently sends an API request to authenticate the Magic Link and log in the User. If this
    * value is not passed, the default invite redirect URL that you set in your Dashboard is used. If you have
    * not set a default sign-up redirect URL, an error is returned.
     */
    public ?string $inviteMagicLinkURL = null;
    /**
    * Set the expiration for the email magic link, in minutes. By default, it expires in 1 hour. The minimum
    * expiration is 5 minutes and the maximum is 7 days (10080 mins).
     */
    public ?int $inviteExpirationMinutes = null;
    /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    *
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), French (`"fr"`) and Brazilian
    * Portuguese (`"pt-br"`); if no value is provided, the copy defaults to English.
    *
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
     */
    public ?string $locale = null;
    /**
    * The `trusted_metadata` field contains an arbitrary JSON object of application-specific data. See the
    * [Metadata](https://stytch.com/docs/api/metadata) reference for complete field behavior details.
     */
    public ?array $trustedMetadata = null;
    /**
    * The `untrusted_metadata` field contains an arbitrary JSON object of application-specific data. Untrusted
    * metadata can be edited by end users directly via the SDK, and **cannot be used to store critical
    * information.** See the [Metadata](https://stytch.com/docs/api/metadata) reference for complete field
    * behavior details.
     */
    public ?array $untrustedMetadata = null;

    public function __construct(
        string $email,
        ?string $inviteTemplateId = null,
        ?\Stytch\Consumer\Models\Attributes $attributes = null,
        ?\Stytch\Consumer\Models\Users\Name $name = null,
        ?string $inviteMagicLinkURL = null,
        ?int $inviteExpirationMinutes = null,
        ?string $locale = null,
        ?array $trustedMetadata = null,
        ?array $untrustedMetadata = null
    ) {
        $this->email = $email;
        $this->inviteTemplateId = $inviteTemplateId;
        $this->attributes = $attributes;
        $this->name = $name;
        $this->inviteMagicLinkURL = $inviteMagicLinkURL;
        $this->inviteExpirationMinutes = $inviteExpirationMinutes;
        $this->locale = $locale;
        $this->trustedMetadata = $trustedMetadata;
        $this->untrustedMetadata = $untrustedMetadata;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['email'],
            $data['invite_template_id'] ?? null,
            $data['attributes'] !== null ? \Stytch\Consumer\Models\Attributes::fromArray($data['attributes']) : null,
            $data['name'] !== null ? \Stytch\Consumer\Models\Users\Name::fromArray($data['name']) : null,
            $data['invite_magic_link_url'] ?? null,
            $data['invite_expiration_minutes'] ?? null,
            $data['locale'] ?? null,
            $data['trusted_metadata'] ?? null,
            $data['untrusted_metadata'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'invite_template_id' => $this->inviteTemplateId,
            'attributes' => $this->attributes,
            'name' => $this->name,
            'invite_magic_link_url' => $this->inviteMagicLinkURL,
            'invite_expiration_minutes' => $this->inviteExpirationMinutes,
            'locale' => $this->locale,
            'trusted_metadata' => $this->trustedMetadata,
            'untrusted_metadata' => $this->untrustedMetadata,
        ];
    }
}
