<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\MagicLinks\Email;

final class LoginOrCreateRequest
{
    /** The email address of the end user. */
    public string $email;
    /**
    * The URL the end user clicks from the login Email Magic Link. This should be a URL that your app receives
    * and parses and subsequently send an API request to authenticate the Magic Link and log in the User. If
    * this value is not passed, the default login redirect URL that you set in your Dashboard is used. If you
    * have not set a default login redirect URL, an error is returned.
     */
    public ?string $loginMagicLinkURL = null;
    /**
    * The URL the end user clicks from the sign-up Email Magic Link. This should be a URL that your app
    * receives and parses and subsequently send an API request to authenticate the Magic Link and sign-up the
    * User. If this value is not passed, the default sign-up redirect URL that you set in your Dashboard is
    * used. If you have not set a default sign-up redirect URL, an error is returned.
     */
    public ?string $signupMagicLinkURL = null;
    /**
    * Set the expiration for the login email magic link, in minutes. By default, it expires in 1 hour. The
    * minimum expiration is 5 minutes and the maximum is 7 days (10080 mins).
     */
    public ?int $loginExpirationMinutes = null;
    /**
    * Set the expiration for the sign-up email magic link, in minutes. By default, it expires in 1 week. The
    * minimum expiration is 5 minutes and the maximum is 7 days (10080 mins).
     */
    public ?int $signupExpirationMinutes = null;
    /**
    * Use a custom template for login emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Login.
     */
    public ?string $loginTemplateId = null;
    /**
    * Use a custom template for sign-up emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Sign-up.
     */
    public ?string $signupTemplateId = null;
    /**
    * Provided attributes to help with fraud detection. These values are pulled and passed into Stytch
    * endpoints by your application.
     */
    public ?\Stytch\Consumer\Models\Attributes $attributes = null;
    /**
    * Flag for whether or not to save a user as pending vs active in Stytch. Defaults to false.
    *         If true, users will be saved with status pending in Stytch's backend until authenticated.
    *         If false, users will be created as active. An example usage of
    *         a true flag would be to require users to verify their phone by entering the OTP code before
    * creating
    *         an account for them.
     */
    public ?bool $createUserAsPending = null;
    /**
    * A base64url encoded SHA256 hash of a one time secret used to validate that the request starts and ends
    * on the same device.
     */
    public ?string $codeChallenge = null;
    /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    *
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), French (`"fr"`) and Brazilian
    * Portuguese (`"pt-br"`); if no value is provided, the copy defaults to English.
    *
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
     */
    public ?string $locale = null;

    public function __construct(
        string $email,
        ?string $loginMagicLinkURL = null,
        ?string $signupMagicLinkURL = null,
        ?int $loginExpirationMinutes = null,
        ?int $signupExpirationMinutes = null,
        ?string $loginTemplateId = null,
        ?string $signupTemplateId = null,
        ?\Stytch\Consumer\Models\Attributes $attributes = null,
        ?bool $createUserAsPending = null,
        ?string $codeChallenge = null,
        ?string $locale = null
    ) {
        $this->email = $email;
        $this->loginMagicLinkURL = $loginMagicLinkURL;
        $this->signupMagicLinkURL = $signupMagicLinkURL;
        $this->loginExpirationMinutes = $loginExpirationMinutes;
        $this->signupExpirationMinutes = $signupExpirationMinutes;
        $this->loginTemplateId = $loginTemplateId;
        $this->signupTemplateId = $signupTemplateId;
        $this->attributes = $attributes;
        $this->createUserAsPending = $createUserAsPending;
        $this->codeChallenge = $codeChallenge;
        $this->locale = $locale;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['email'],
            $data['login_magic_link_url'] ?? null,
            $data['signup_magic_link_url'] ?? null,
            $data['login_expiration_minutes'] ?? null,
            $data['signup_expiration_minutes'] ?? null,
            $data['login_template_id'] ?? null,
            $data['signup_template_id'] ?? null,
            isset($data['attributes']) && $data['attributes'] !== null ? \Stytch\Consumer\Models\Attributes::fromArray($data['attributes']) : null,
            $data['create_user_as_pending'] ?? null,
            $data['code_challenge'] ?? null,
            $data['locale'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'login_magic_link_url' => $this->loginMagicLinkURL,
            'signup_magic_link_url' => $this->signupMagicLinkURL,
            'login_expiration_minutes' => $this->loginExpirationMinutes,
            'signup_expiration_minutes' => $this->signupExpirationMinutes,
            'login_template_id' => $this->loginTemplateId,
            'signup_template_id' => $this->signupTemplateId,
            'attributes' => $this->attributes,
            'create_user_as_pending' => $this->createUserAsPending,
            'code_challenge' => $this->codeChallenge,
            'locale' => $this->locale,
        ];
    }
}
