<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\IDP\OAuth;

final class AuthorizeResponse
{
    public string $requestId;
    public string $redirectUri;
    public int $statusCode;
    public ?string $authorizationCode = null;

    public function __construct(
        string $requestId,
        string $redirectUri,
        int $statusCode,
        ?string $authorizationCode = null
    ) {
        $this->requestId = $requestId;
        $this->redirectUri = $redirectUri;
        $this->statusCode = $statusCode;
        $this->authorizationCode = $authorizationCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['redirect_uri'],
            $data['status_code'],
            $data['authorization_code'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'redirect_uri' => $this->redirectUri,
            'status_code' => $this->statusCode,
            'authorization_code' => $this->authorizationCode,
        ];
    }
}
