<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\ConnectedApp;

final class ConnectedAppPublic
{
    public string $clientId;
    public string $clientName;
    public string $clientDescription;
    public string $clientType;
    public ?string $logoURL = null;

    public function __construct(
        string $clientId,
        string $clientName,
        string $clientDescription,
        string $clientType,
        ?string $logoURL = null
    ) {
        $this->clientId = $clientId;
        $this->clientName = $clientName;
        $this->clientDescription = $clientDescription;
        $this->clientType = $clientType;
        $this->logoURL = $logoURL;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['client_id'],
            $data['client_name'],
            $data['client_description'],
            $data['client_type'],
            $data['logo_url'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'client_id' => $this->clientId,
            'client_name' => $this->clientName,
            'client_description' => $this->clientDescription,
            'client_type' => $this->clientType,
            'logo_url' => $this->logoURL,
        ];
    }
}
