<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\ConnectedApp;

final class SearchConnectedAppsOperand
{
    public array $clientIds;
    public array $clientTypes;
    public array $creationMethods;
    public ?string $filter = null;
    public ?string $clientNamePrefix = null;

    public function __construct(
        array $clientIds,
        array $clientTypes,
        array $creationMethods,
        ?string $filter = null,
        ?string $clientNamePrefix = null
    ) {
        $this->clientIds = $clientIds;
        $this->clientTypes = $clientTypes;
        $this->creationMethods = $creationMethods;
        $this->filter = $filter;
        $this->clientNamePrefix = $clientNamePrefix;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['client_ids'],
            $data['client_types'],
            $data['creation_methods'],
            $data['filter'] ?? null,
            $data['client_name_prefix'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'client_ids' => $this->clientIds,
            'client_types' => $this->clientTypes,
            'creation_methods' => $this->creationMethods,
            'filter' => $this->filter,
            'client_name_prefix' => $this->clientNamePrefix,
        ];
    }
}
