<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\OAuth;

final class AuthenticateResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /** The unique ID of the affected User. */
    public string $userId;
    /**
    * The unique identifier for the User within a given OAuth provider. Also commonly called the "sub" or
    * "Subject field" in OAuth protocols.
     */
    public string $providerSubject;
    /**
    * Denotes the OAuth identity provider that the user has authenticated with, e.g. Google, Facebook, GitHub
    * etc.
     */
    public string $providerType;
    /** A secret token for a given Stytch Session. */
    public string $sessionToken;
    /** The JSON Web Token (JWT) for a given Stytch Session. */
    public string $sessionJwt;
    /**
    * The `provider_values` object lists relevant identifiers, values, and scopes for a given OAuth provider.
    * For example this object will include a provider's `access_token` that you can use to access the
    * provider's API for a given user.
    *
    *   Note that these values will vary based on the OAuth provider in question, e.g. `id_token` is only
    * returned by OIDC compliant identity providers.
     */
    public ProviderValues $providerValues;
    /**
    * The `user` object affected by this API call. See the
    * [Get user endpoint](https://stytch.com/docs/api/get-user) for complete response field details.
     */
    public \Stytch\Consumer\Models\Users\User $user;
    /**
    * Indicates if all other of the User's Sessions need to be reset. You should check this field if you
    * aren't using Stytch's Session product. If you are using Stytch's Session product, we revoke the User's
    * other sessions for you.
     */
    public bool $resetSessions;
    /** The unique ID for an OAuth registration. */
    public string $oauthUserRegistrationId;
    /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
     */
    public int $statusCode;
    /**
    * A `Session` object. For backwards compatibility reasons, the session from an OAuth authenticate call is
    * labeled as `user_session`, but is otherwise just a standard stytch `Session` object.
    *
    *   See [Session object](https://stytch.com/docs/api/session-object) for complete response fields.
     */
    public ?\Stytch\Consumer\Models\Sessions\Session $userSession = null;
    /**
    * If a valid `telemetry_id` was passed in the request and the
    * [Fingerprint Lookup API](https://stytch.com/docs/fraud/api/fingerprint-lookup) returned results, the
    * `user_device` response field will contain information about the user's device attributes.
     */
    public ?\Stytch\Consumer\Models\DeviceInfo $userDevice = null;

    public function __construct(
        string $requestId,
        string $userId,
        string $providerSubject,
        string $providerType,
        string $sessionToken,
        string $sessionJwt,
        ProviderValues $providerValues,
        \Stytch\Consumer\Models\Users\User $user,
        bool $resetSessions,
        string $oauthUserRegistrationId,
        int $statusCode,
        ?\Stytch\Consumer\Models\Sessions\Session $userSession = null,
        ?\Stytch\Consumer\Models\DeviceInfo $userDevice = null
    ) {
        $this->requestId = $requestId;
        $this->userId = $userId;
        $this->providerSubject = $providerSubject;
        $this->providerType = $providerType;
        $this->sessionToken = $sessionToken;
        $this->sessionJwt = $sessionJwt;
        $this->providerValues = $providerValues;
        $this->user = $user;
        $this->resetSessions = $resetSessions;
        $this->oauthUserRegistrationId = $oauthUserRegistrationId;
        $this->statusCode = $statusCode;
        $this->userSession = $userSession;
        $this->userDevice = $userDevice;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['user_id'],
            $data['provider_subject'],
            $data['provider_type'],
            $data['session_token'],
            $data['session_jwt'],
            ProviderValues::fromArray($data['provider_values']),
            \Stytch\Consumer\Models\Users\User::fromArray($data['user']),
            $data['reset_sessions'],
            $data['oauth_user_registration_id'],
            $data['status_code'],
            $data['user_session'] !== null ? \Stytch\Consumer\Models\Sessions\Session::fromArray($data['user_session']) : null,
            $data['user_device'] !== null ? \Stytch\Consumer\Models\DeviceInfo::fromArray($data['user_device']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'user_id' => $this->userId,
            'provider_subject' => $this->providerSubject,
            'provider_type' => $this->providerType,
            'session_token' => $this->sessionToken,
            'session_jwt' => $this->sessionJwt,
            'provider_values' => $this->providerValues,
            'user' => $this->user,
            'reset_sessions' => $this->resetSessions,
            'oauth_user_registration_id' => $this->oauthUserRegistrationId,
            'status_code' => $this->statusCode,
            'user_session' => $this->userSession,
            'user_device' => $this->userDevice,
        ];
    }
}
