<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\M2M\Clients;

final class UpdateRequest
{
    /** The ID of the client. */
    public string $clientId;
    /** A human-readable name for the client. */
    public ?string $clientName = null;
    /** A human-readable description for the client. */
    public ?string $clientDescription = null;
    /** The status of the client - either `active` or `inactive`. */
    public ?string $status = null;
    /** An array of scopes assigned to the client. */
    public ?array $scopes = null;
    /**
    * The `trusted_metadata` field contains an arbitrary JSON object of application-specific data. See the
    * [Metadata](https://stytch.com/docs/api/metadata) reference for complete field behavior details.
     */
    public ?array $trustedMetadata = null;

    public function __construct(
        string $clientId,
        ?string $clientName = null,
        ?string $clientDescription = null,
        ?string $status = null,
        ?array $scopes = null,
        ?array $trustedMetadata = null
    ) {
        $this->clientId = $clientId;
        $this->clientName = $clientName;
        $this->clientDescription = $clientDescription;
        $this->status = $status;
        $this->scopes = $scopes;
        $this->trustedMetadata = $trustedMetadata;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['client_id'],
            $data['client_name'] ?? null,
            $data['client_description'] ?? null,
            $data['status'] ?? null,
            $data['scopes'] ?? null,
            $data['trusted_metadata'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'client_id' => $this->clientId,
            'client_name' => $this->clientName,
            'client_description' => $this->clientDescription,
            'status' => $this->status,
            'scopes' => $this->scopes,
            'trusted_metadata' => $this->trustedMetadata,
        ];
    }
}
