<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Api;

use Stytch\Core\Client;

class ConnectedApp
{
    private Client $client;

    public ConnectedAppClients $clients;

    public function __construct(Client $client)
    {
        $this->client = $client;

        $this->clients = new ConnectedAppClients($this->client);
    }

}
