<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Api;

use Stytch\Core\Client;

class Sessions
{
    private Client $client;
    private string $projectId;


    public function __construct(Client $client, string $projectId)
    {
        $this->client = $client;
        $this->projectId = $projectId;

    }

}
