<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\TOTPs;

class CreateResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /** Globally unique UUID that identifies a specific Member. */
    public string $memberId;
    /** The unique ID for a TOTP instance. */
    public string $totpRegistrationId;
    /** The TOTP secret key shared between the authenticator app and the server used to generate TOTP codes. */
    public string $secret;
    /** The QR code image encoded in base64. */
    public string $qrCode;
    /** An array of recovery codes that can be used to recover a Member's account. */
    public array $recoveryCodes;
    /** The [Member object](https://stytch.com/docs/b2b/api/member-object) */
    public \Stytch\B2B\Models\Organizations\Member $member;
    /** The [Organization object](https://stytch.com/docs/b2b/api/organization-object). */
    public \Stytch\B2B\Models\Organizations\Organization $organization;
    /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
     */
    public int $statusCode;

    public function __construct(
        string $requestId,
        string $memberId,
        string $totpRegistrationId,
        string $secret,
        string $qrCode,
        array $recoveryCodes,
        \Stytch\B2B\Models\Organizations\Member $member,
        \Stytch\B2B\Models\Organizations\Organization $organization,
        int $statusCode
    ) {
        $this->requestId = $requestId;
        $this->memberId = $memberId;
        $this->totpRegistrationId = $totpRegistrationId;
        $this->secret = $secret;
        $this->qrCode = $qrCode;
        $this->recoveryCodes = $recoveryCodes;
        $this->member = $member;
        $this->organization = $organization;
        $this->statusCode = $statusCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['member_id'],
            $data['totp_registration_id'],
            $data['secret'],
            $data['qr_code'],
            $data['recovery_codes'],
            \Stytch\B2B\Models\Organizations\Member::fromArray($data['member']),
            \Stytch\B2B\Models\Organizations\Organization::fromArray($data['organization']),
            $data['status_code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'member_id' => $this->memberId,
            'totp_registration_id' => $this->totpRegistrationId,
            'secret' => $this->secret,
            'qr_code' => $this->qrCode,
            'recovery_codes' => $this->recoveryCodes,
            'member' => $this->member,
            'organization' => $this->organization,
            'status_code' => $this->statusCode,
        ];
    }
}
