<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models;

class AuthenticateMemberImpersonationTokenResponse
{
    public string $member_id;
    public string $organization_id;
    public Member $member;
    public string $session_token;
    public string $session_jwt;
    public ?MemberSession $member_session;
    public Organization $organization;
    public string $intermediate_session_token;
    public bool $member_authenticated;
    public ?MfaRequired $mfa_required;

    public function __construct(
        string $member_id,
        string $organization_id,
        Member $member,
        string $session_token,
        string $session_jwt,
        ?MemberSession $member_session,
        Organization $organization,
        string $intermediate_session_token,
        bool $member_authenticated,
        ?MfaRequired $mfa_required
    ) {
        $this->member_id = $member_id;
        $this->organization_id = $organization_id;
        $this->member = $member;
        $this->session_token = $session_token;
        $this->session_jwt = $session_jwt;
        $this->member_session = $member_session;
        $this->organization = $organization;
        $this->intermediate_session_token = $intermediate_session_token;
        $this->member_authenticated = $member_authenticated;
        $this->mfa_required = $mfa_required;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['organization_id'],
            $data['member'],
            $data['session_token'],
            $data['session_jwt'],
            $data['member_session'] ?? null,
            $data['organization'],
            $data['intermediate_session_token'],
            $data['member_authenticated'],
            $data['mfa_required'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'organization_id' => $this->organization_id,
            'member' => $this->member,
            'session_token' => $this->session_token,
            'session_jwt' => $this->session_jwt,
            'member_session' => $this->member_session,
            'organization' => $this->organization,
            'intermediate_session_token' => $this->intermediate_session_token,
            'member_authenticated' => $this->member_authenticated,
            'mfa_required' => $this->mfa_required,
        ];
    }
}

