<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models;

enum UpdateRequestStatus: string
{
}

class CreateResponse
{
    public M2MClientWithClientSecret $m2m_client;

    public function __construct(
        M2MClientWithClientSecret $m2m_client
    ) {
        $this->m2m_client = $m2m_client;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['m2m_client']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'm2m_client' => $this->m2m_client,
        ];
    }
}

class DeleteResponse
{
    public string $client_id;

    public function __construct(
        string $client_id
    ) {
        $this->client_id = $client_id;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['client_id']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'client_id' => $this->client_id,
        ];
    }
}

class GetResponse
{
    public M2MClient $m2m_client;

    public function __construct(
        M2MClient $m2m_client
    ) {
        $this->m2m_client = $m2m_client;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['m2m_client']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'm2m_client' => $this->m2m_client,
        ];
    }
}

class SearchResponse
{
    public array $m2m_clients;
    public ResultsMetadata $results_metadata;

    public function __construct(
        array $m2m_clients,
        ResultsMetadata $results_metadata
    ) {
        $this->m2m_clients = $m2m_clients;
        $this->results_metadata = $results_metadata;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['m2m_clients'],
            $data['results_metadata']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'm2m_clients' => $this->m2m_clients,
            'results_metadata' => $this->results_metadata,
        ];
    }
}

class UpdateResponse
{
    public M2MClient $m2m_client;

    public function __construct(
        M2MClient $m2m_client
    ) {
        $this->m2m_client = $m2m_client;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['m2m_client']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'm2m_client' => $this->m2m_client,
        ];
    }
}

