<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models;

class AuthenticateResponse
{
    public string $member_id;
    public string $method_id;
    public bool $reset_sessions;
    public string $organization_id;
    public Member $member;
    public string $session_token;
    public string $session_jwt;
    public ?MemberSession $member_session;
    public Organization $organization;
    public string $intermediate_session_token;
    public bool $member_authenticated;
    public ?MfaRequired $mfa_required;
    public ?PrimaryRequired $primary_required;
    public ?DeviceInfo $member_device;

    public function __construct(
        string $member_id,
        string $method_id,
        bool $reset_sessions,
        string $organization_id,
        Member $member,
        string $session_token,
        string $session_jwt,
        ?MemberSession $member_session,
        Organization $organization,
        string $intermediate_session_token,
        bool $member_authenticated,
        ?MfaRequired $mfa_required,
        ?PrimaryRequired $primary_required,
        ?DeviceInfo $member_device
    ) {
        $this->member_id = $member_id;
        $this->method_id = $method_id;
        $this->reset_sessions = $reset_sessions;
        $this->organization_id = $organization_id;
        $this->member = $member;
        $this->session_token = $session_token;
        $this->session_jwt = $session_jwt;
        $this->member_session = $member_session;
        $this->organization = $organization;
        $this->intermediate_session_token = $intermediate_session_token;
        $this->member_authenticated = $member_authenticated;
        $this->mfa_required = $mfa_required;
        $this->primary_required = $primary_required;
        $this->member_device = $member_device;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['method_id'],
            $data['reset_sessions'],
            $data['organization_id'],
            $data['member'],
            $data['session_token'],
            $data['session_jwt'],
            $data['member_session'] ?? null,
            $data['organization'],
            $data['intermediate_session_token'],
            $data['member_authenticated'],
            $data['mfa_required'] ?? null,
            $data['primary_required'] ?? null,
            $data['member_device'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'method_id' => $this->method_id,
            'reset_sessions' => $this->reset_sessions,
            'organization_id' => $this->organization_id,
            'member' => $this->member,
            'session_token' => $this->session_token,
            'session_jwt' => $this->session_jwt,
            'member_session' => $this->member_session,
            'organization' => $this->organization,
            'intermediate_session_token' => $this->intermediate_session_token,
            'member_authenticated' => $this->member_authenticated,
            'mfa_required' => $this->mfa_required,
            'primary_required' => $this->primary_required,
            'member_device' => $this->member_device,
        ];
    }
}

class EmailDiscoverySendResponse
{

    public function __construct(
    ) {
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
        ];
    }
}

class DiscoveryAuthenticateResponse
{
    public string $intermediate_session_token;
    public string $email_address;
    public ?array $discovered_organizations;

    public function __construct(
        string $intermediate_session_token,
        string $email_address,
        ?array $discovered_organizations
    ) {
        $this->intermediate_session_token = $intermediate_session_token;
        $this->email_address = $email_address;
        $this->discovered_organizations = $discovered_organizations;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['intermediate_session_token'],
            $data['email_address'],
            $data['discovered_organizations'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'intermediate_session_token' => $this->intermediate_session_token,
            'email_address' => $this->email_address,
            'discovered_organizations' => $this->discovered_organizations,
        ];
    }
}

class EmailInviteResponse
{
    public string $member_id;
    public Member $member;
    public Organization $organization;

    public function __construct(
        string $member_id,
        Member $member,
        Organization $organization
    ) {
        $this->member_id = $member_id;
        $this->member = $member;
        $this->organization = $organization;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['member'],
            $data['organization']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'member' => $this->member,
            'organization' => $this->organization,
        ];
    }
}

class EmailLoginOrSignupResponse
{
    public string $member_id;
    public bool $member_created;
    public Member $member;
    public Organization $organization;

    public function __construct(
        string $member_id,
        bool $member_created,
        Member $member,
        Organization $organization
    ) {
        $this->member_id = $member_id;
        $this->member_created = $member_created;
        $this->member = $member;
        $this->organization = $organization;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['member_created'],
            $data['member'],
            $data['organization']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'member_created' => $this->member_created,
            'member' => $this->member,
            'organization' => $this->organization,
        ];
    }
}

class EmailInviteRequestOptions
{
    public ?mixed $authorization;

    public function __construct(
        ?mixed $authorization
    ) {
        $this->authorization = $authorization;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['authorization'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'authorization' => $this->authorization,
        ];
    }
}

