<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models;

enum AuthenticateRequestLocale: string
{
}

class ProviderValues
{
    public array $scopes;
    public ?string $access_token;
    public ?string $refresh_token;
    public ?string $expires_at;
    public ?string $id_token;

    public function __construct(
        array $scopes,
        ?string $access_token,
        ?string $refresh_token,
        ?string $expires_at,
        ?string $id_token
    ) {
        $this->scopes = $scopes;
        $this->access_token = $access_token;
        $this->refresh_token = $refresh_token;
        $this->expires_at = $expires_at;
        $this->id_token = $id_token;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['scopes'],
            $data['access_token'] ?? null,
            $data['refresh_token'] ?? null,
            $data['expires_at'] ?? null,
            $data['id_token'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'scopes' => $this->scopes,
            'access_token' => $this->access_token,
            'refresh_token' => $this->refresh_token,
            'expires_at' => $this->expires_at,
            'id_token' => $this->id_token,
        ];
    }
}

class AuthenticateResponse
{
    public string $member_id;
    public string $provider_subject;
    public string $provider_type;
    public string $session_token;
    public string $session_jwt;
    public Member $member;
    public string $organization_id;
    public Organization $organization;
    public bool $reset_sessions;
    public bool $member_authenticated;
    public string $intermediate_session_token;
    public ?MemberSession $member_session;
    public ?ProviderValues $provider_values;
    public ?MfaRequired $mfa_required;
    public ?PrimaryRequired $primary_required;
    public ?DeviceInfo $member_device;

    public function __construct(
        string $member_id,
        string $provider_subject,
        string $provider_type,
        string $session_token,
        string $session_jwt,
        Member $member,
        string $organization_id,
        Organization $organization,
        bool $reset_sessions,
        bool $member_authenticated,
        string $intermediate_session_token,
        ?MemberSession $member_session,
        ?ProviderValues $provider_values,
        ?MfaRequired $mfa_required,
        ?PrimaryRequired $primary_required,
        ?DeviceInfo $member_device
    ) {
        $this->member_id = $member_id;
        $this->provider_subject = $provider_subject;
        $this->provider_type = $provider_type;
        $this->session_token = $session_token;
        $this->session_jwt = $session_jwt;
        $this->member = $member;
        $this->organization_id = $organization_id;
        $this->organization = $organization;
        $this->reset_sessions = $reset_sessions;
        $this->member_authenticated = $member_authenticated;
        $this->intermediate_session_token = $intermediate_session_token;
        $this->member_session = $member_session;
        $this->provider_values = $provider_values;
        $this->mfa_required = $mfa_required;
        $this->primary_required = $primary_required;
        $this->member_device = $member_device;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['provider_subject'],
            $data['provider_type'],
            $data['session_token'],
            $data['session_jwt'],
            $data['member'],
            $data['organization_id'],
            $data['organization'],
            $data['reset_sessions'],
            $data['member_authenticated'],
            $data['intermediate_session_token'],
            $data['member_session'] ?? null,
            $data['provider_values'] ?? null,
            $data['mfa_required'] ?? null,
            $data['primary_required'] ?? null,
            $data['member_device'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'provider_subject' => $this->provider_subject,
            'provider_type' => $this->provider_type,
            'session_token' => $this->session_token,
            'session_jwt' => $this->session_jwt,
            'member' => $this->member,
            'organization_id' => $this->organization_id,
            'organization' => $this->organization,
            'reset_sessions' => $this->reset_sessions,
            'member_authenticated' => $this->member_authenticated,
            'intermediate_session_token' => $this->intermediate_session_token,
            'member_session' => $this->member_session,
            'provider_values' => $this->provider_values,
            'mfa_required' => $this->mfa_required,
            'primary_required' => $this->primary_required,
            'member_device' => $this->member_device,
        ];
    }
}

