<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models;

enum SendRequestLocale: string
{
}

class AuthenticateResponse
{
    public string $member_id;
    public Member $member;
    public Organization $organization;
    public string $session_token;
    public string $session_jwt;
    public ?MemberSession $member_session;
    public ?DeviceInfo $member_device;

    public function __construct(
        string $member_id,
        Member $member,
        Organization $organization,
        string $session_token,
        string $session_jwt,
        ?MemberSession $member_session,
        ?DeviceInfo $member_device
    ) {
        $this->member_id = $member_id;
        $this->member = $member;
        $this->organization = $organization;
        $this->session_token = $session_token;
        $this->session_jwt = $session_jwt;
        $this->member_session = $member_session;
        $this->member_device = $member_device;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['member'],
            $data['organization'],
            $data['session_token'],
            $data['session_jwt'],
            $data['member_session'] ?? null,
            $data['member_device'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'member' => $this->member,
            'organization' => $this->organization,
            'session_token' => $this->session_token,
            'session_jwt' => $this->session_jwt,
            'member_session' => $this->member_session,
            'member_device' => $this->member_device,
        ];
    }
}

class SendResponse
{
    public string $member_id;
    public Member $member;
    public Organization $organization;

    public function __construct(
        string $member_id,
        Member $member,
        Organization $organization
    ) {
        $this->member_id = $member_id;
        $this->member = $member;
        $this->organization = $organization;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['member'],
            $data['organization']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->member_id,
            'member' => $this->member,
            'organization' => $this->organization,
        ];
    }
}

