<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations;

final class ActiveSCIMConnection
{
    /** The ID of the SCIM connection. */
    public string $connectionId;
    /** A human-readable display name for the connection. */
    public string $displayName;
    public string $bearerTokenLastFour;
    public ?string $bearerTokenExpiresAt = null;

    public function __construct(
        string $connectionId,
        string $displayName,
        string $bearerTokenLastFour,
        ?string $bearerTokenExpiresAt = null
    ) {
        $this->connectionId = $connectionId;
        $this->displayName = $displayName;
        $this->bearerTokenLastFour = $bearerTokenLastFour;
        $this->bearerTokenExpiresAt = $bearerTokenExpiresAt;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['connection_id'],
            $data['display_name'],
            $data['bearer_token_last_four'],
            $data['bearer_token_expires_at'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'connection_id' => $this->connectionId,
            'display_name' => $this->displayName,
            'bearer_token_last_four' => $this->bearerTokenLastFour,
            'bearer_token_expires_at' => $this->bearerTokenExpiresAt,
        ];
    }
}
