<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations;

class ConnectedAppsResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    public array $connectedApps;
    public int $statusCode;

    public function __construct(
        string $requestId,
        array $connectedApps,
        int $statusCode
    ) {
        $this->requestId = $requestId;
        $this->connectedApps = $connectedApps;
        $this->statusCode = $statusCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            isset($data['connected_apps']) ? array_map(fn ($item) => OrganizationConnectedApp::fromArray($item), $data['connected_apps']) : [],
            $data['status_code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'connected_apps' => $this->connectedApps,
            'status_code' => $this->statusCode,
        ];
    }
}
