<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations;

final class CustomRolePermission
{
    public string $resourceId;
    public array $actions;

    public function __construct(
        string $resourceId,
        array $actions
    ) {
        $this->resourceId = $resourceId;
        $this->actions = $actions;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['resource_id'],
            $data['actions']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'resource_id' => $this->resourceId,
            'actions' => $this->actions,
        ];
    }
}
