<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations;

final class MemberRole
{
    /**
    * The unique identifier of the RBAC Role, provided by the developer and intended to be human-readable.
    *
    *   Reserved `role_id`s that are predefined by Stytch include:
    *
    *   * `stytch_member`
    *   * `stytch_admin`
    *
    *   Check out the [guide on Stytch default Roles](https://stytch.com/docs/b2b/guides/rbac/stytch-default)
    * for a more detailed explanation.
     */
    public string $roleId;
    /**
    * A list of sources for this role assignment. A role assignment can come from multiple sources - for
    * example, the Role could be both explicitly assigned and implicitly granted from the Member's email
    * domain.
     */
    public array $sources;

    public function __construct(
        string $roleId,
        array $sources
    ) {
        $this->roleId = $roleId;
        $this->sources = $sources;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['role_id'],
            isset($data['sources']) ? array_map(fn($item) => MemberRoleSource::fromArray($item), $data['sources']) : []
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'role_id' => $this->roleId,
            'sources' => $this->sources,
        ];
    }
}
