<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations;

class OIDCProviderInfo
{
    /**
    * The unique identifier for the User within a given OAuth provider. Also commonly called the `sub` or
    * "Subject field" in OAuth protocols.
     */
    public string $providerSubject;
    /**
    * The `id_token` returned by the OAuth provider. ID Tokens are JWTs that contain structured information
    * about a user. The exact content of each ID Token varies from provider to provider. ID Tokens are
    * returned from OAuth providers that conform to the [OpenID Connect](https://openid.net/foundation/)
    * specification, which is based on OAuth.
     */
    public string $idToken;
    /** The `access_token` that you may use to access the User's data in the provider's API. */
    public string $accessToken;
    /** The number of seconds until the access token expires. */
    public int $accessTokenExpiresIn;
    /**
    * The OAuth scopes included for a given provider. See each provider's section above to see which scopes
    * are included by default and how to add custom scopes.
     */
    public array $scopes;
    /** Globally unique UUID that identifies a specific SSO `connection_id` for a Member. */
    public string $connectionId;
    /**
    * The `refresh_token` that you may use to obtain a new `access_token` for the User within the provider's
    * API.
     */
    public ?string $refreshToken = null;

    public function __construct(
        string $providerSubject,
        string $idToken,
        string $accessToken,
        int $accessTokenExpiresIn,
        array $scopes,
        string $connectionId,
        ?string $refreshToken = null
    ) {
        $this->providerSubject = $providerSubject;
        $this->idToken = $idToken;
        $this->accessToken = $accessToken;
        $this->accessTokenExpiresIn = $accessTokenExpiresIn;
        $this->scopes = $scopes;
        $this->connectionId = $connectionId;
        $this->refreshToken = $refreshToken;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['provider_subject'],
            $data['id_token'],
            $data['access_token'],
            $data['access_token_expires_in'],
            $data['scopes'],
            $data['connection_id'],
            $data['refresh_token'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'provider_subject' => $this->providerSubject,
            'id_token' => $this->idToken,
            'access_token' => $this->accessToken,
            'access_token_expires_in' => $this->accessTokenExpiresIn,
            'scopes' => $this->scopes,
            'connection_id' => $this->connectionId,
            'refresh_token' => $this->refreshToken,
        ];
    }
}
