<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Organizations;

final class OrganizationConnectedAppActiveMember
{
    /** Globally unique UUID that identifies a specific Member. */
    public string $memberId;
    /** Scopes that were granted at the completion of the last authorization flow. */
    public array $grantedScopes;

    public function __construct(
        string $memberId,
        array $grantedScopes
    ) {
        $this->memberId = $memberId;
        $this->grantedScopes = $grantedScopes;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['member_id'],
            $data['granted_scopes']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'member_id' => $this->memberId,
            'granted_scopes' => $this->grantedScopes,
        ];
    }
}
