<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Fraud\Rules;


final class ListResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /**
    * The `next_cursor` string is returned when your result contains more than one page of results. This value
    * is passed into your next request in the `cursor` field.
     */
    public string $nextCursor;
    /** A list of rules for the project */
    public array $rules;
    /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
     */
    public int $statusCode;

    public function __construct(
        string $requestId,
        string $nextCursor,
        array $rules,
        int $statusCode
    ) {
        $this->requestId = $requestId;
        $this->nextCursor = $nextCursor;
        $this->rules = $rules;
        $this->statusCode = $statusCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['next_cursor'],
            isset($data['rules']) ? array_map(fn($item) => \Stytch\Consumer\Models\Fraud\Rule::fromArray($item), $data['rules']) : [],
            $data['status_code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'next_cursor' => $this->nextCursor,
            'rules' => $this->rules,
            'status_code' => $this->statusCode,
        ];
    }
}