<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Fraud\Rules;


final class ListRequest
{
    /**
    * The `cursor` field allows you to paginate through your results. Each result array is limited to 100
    * results. If your query returns more than 100 results, you will need to paginate the responses using the
    * `cursor`. If you receive a response that includes a non-null `next_cursor`, repeat the request with the
    * `next_cursor` value set to the `cursor` field to retrieve the next page of results. Continue to make
    * requests until the `next_cursor` in the response is null.
     */
    public ?string $cursor = null;
    /**
    * The number of results to return per page. The default limit is 10. A maximum of 100 results can be
    * returned by a single get request. If the total size of your result set is greater than one page size,
    * you must paginate the response. See the `cursor` field.
     */
    public ?int $limit = null;

    public function __construct(
        ?string $cursor = null,
        ?int $limit = null
    ) {
        $this->cursor = $cursor;
        $this->limit = $limit;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['cursor'] ?? null,
            $data['limit'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'cursor' => $this->cursor,
            'limit' => $this->limit,
        ];
    }
}