<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\OTPs\Email\Discovery;


final class AuthenticateRequest
{
    /** The email address of the Member. */
    public string $emailAddress;
    /** The code to authenticate. */
    public string $code;

    public function __construct(
        string $emailAddress,
        string $code
    ) {
        $this->emailAddress = $emailAddress;
        $this->code = $code;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['email_address'],
            $data['code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'email_address' => $this->emailAddress,
            'code' => $this->code,
        ];
    }
}