<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Passwords\Email;

class ResetStartRequest
{
    /** The email of the User that requested the password reset. */
    public string $email;
    /**
    * The url that the user clicks from the password reset email to finish the reset password flow.
    *   This should be a url that your app receives and parses before showing your app's reset password page.
    *   After the user submits a new password to your app, it should send an API request to complete the
    * password reset process.
    *   If this value is not passed, the default reset password redirect URL that you set in your Dashboard is
    * used.
    *   If you have not set a default reset password redirect URL, an error is returned.
     */
    public ?string $resetPasswordRedirectURL = null;
    /**
    * Set the expiration for the password reset, in minutes. By default, it expires in 30 minutes.
    *   The minimum expiration is 5 minutes and the maximum is 7 days (10080 mins).
     */
    public ?int $resetPasswordExpirationMinutes = null;
    /**
    * A base64url encoded SHA256 hash of a one time secret used to validate that the request starts and ends
    * on the same device.
     */
    public ?string $codeChallenge = null;
    /**
    * Provided attributes to help with fraud detection. These values are pulled and passed into Stytch
    * endpoints by your application.
     */
    public ?\Stytch\Consumer\Models\Attributes $attributes = null;
    /**
    * The URL Stytch redirects to after the OAuth flow is completed for a user that already exists. This URL
    * should be a route in your application which will run `oauth.authenticate` (see below) and finish the
    * login.
    *
    *   The URL must be configured as a Login URL in the
    * [Redirect URL page](https://stytch.com/dashboard/redirect-urls). If the field is not specified, the
    * default Login URL will be used.
     */
    public ?string $loginRedirectURL = null;
    /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    *
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), French (`"fr"`) and Brazilian
    * Portuguese (`"pt-br"`); if no value is provided, the copy defaults to English.
    *
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
     */
    public ?string $locale = null;
    /**
    * Use a custom template for password reset emails. By default, it will use your default email template.
    *   The template must be a template using our built-in customizations or a custom HTML email for Passwords
    * - Password reset.
     */
    public ?string $resetPasswordTemplateId = null;

    public function __construct(
        string $email,
        ?string $resetPasswordRedirectURL = null,
        ?int $resetPasswordExpirationMinutes = null,
        ?string $codeChallenge = null,
        ?\Stytch\Consumer\Models\Attributes $attributes = null,
        ?string $loginRedirectURL = null,
        ?string $locale = null,
        ?string $resetPasswordTemplateId = null
    ) {
        $this->email = $email;
        $this->resetPasswordRedirectURL = $resetPasswordRedirectURL;
        $this->resetPasswordExpirationMinutes = $resetPasswordExpirationMinutes;
        $this->codeChallenge = $codeChallenge;
        $this->attributes = $attributes;
        $this->loginRedirectURL = $loginRedirectURL;
        $this->locale = $locale;
        $this->resetPasswordTemplateId = $resetPasswordTemplateId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['email'],
            $data['reset_password_redirect_url'] ?? null,
            $data['reset_password_expiration_minutes'] ?? null,
            $data['code_challenge'] ?? null,
            $data['attributes'] !== null ? \Stytch\Consumer\Models\Attributes::fromArray($data['attributes']) : null,
            $data['login_redirect_url'] ?? null,
            $data['locale'] ?? null,
            $data['reset_password_template_id'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'email' => $this->email,
            'reset_password_redirect_url' => $this->resetPasswordRedirectURL,
            'reset_password_expiration_minutes' => $this->resetPasswordExpirationMinutes,
            'code_challenge' => $this->codeChallenge,
            'attributes' => $this->attributes,
            'login_redirect_url' => $this->loginRedirectURL,
            'locale' => $this->locale,
            'reset_password_template_id' => $this->resetPasswordTemplateId,
        ];
    }
}
