<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Passwords\Email;

final class ResetStartRequest
{
    /**
    * Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to
    * perform operations on an Organization, so be sure to preserve this value. You may also use the
    * organization_slug or organization_external_id here as a convenience.
     */
    public string $organizationId;
    /** The email address of the Member to start the email reset process for. */
    public string $emailAddress;
    /**
    * The URL that the Member clicks from the reset password link. This URL should be an endpoint in the
    * backend server that verifies the request by querying
    *   Stytch's authenticate endpoint and finishes the reset password flow. If this value is not passed, the
    * default `reset_password_redirect_url` that you set in your Dashboard is used.
    *   If you have not set a default `reset_password_redirect_url`, an error is returned.
     */
    public ?string $resetPasswordRedirectURL = null;
    /**
    * Sets a time limit after which the email link to reset the member's password will no longer be valid. The
    * minimum allowed expiration is 5 minutes and the maximum is 10080 minutes (7 days). By default, the
    * expiration is 30 minutes.
     */
    public ?int $resetPasswordExpirationMinutes = null;
    /**
    * A base64url encoded SHA256 hash of a one time secret used to validate that the request starts and ends
    * on the same device.
     */
    public ?string $codeChallenge = null;
    /**
    * The URL that Members are redirected to upon clicking the "Log in without password" button in password
    * reset emails.
    *
    *       After Members are redirected to the login redirect URL, your application should retrieve the
    * `token` value from the URL parameters and call the
    * [Magic Link Authenticate endpoint](https://stytch.com/docs/api/authenticate-magic-link) to log the
    * Member in without requiring a password reset. If this value is not provided, your project's default
    * login redirect URL will be used. If you have not set a default login redirect URL, an error will be
    * returned.
     */
    public ?string $loginRedirectURL = null;
    /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    *
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), French (`"fr"`) and Brazilian
    * Portuguese (`"pt-br"`); if no value is provided, the copy defaults to English.
    *
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
     */
    public ?string $locale = null;
    /**
    * Use a custom template for reset password emails. By default, it will use your default email template.
    * The template must be a template using our built-in customizations or a custom HTML email for Passwords -
    * Reset Password.
     */
    public ?string $resetPasswordTemplateId = null;
    /**
    * Use a custom template for verification emails sent during password reset flows. When cross-organization
    * passwords are enabled for your Project, this template will be used the first time a user sets a password
    * via a
    *   password reset flow. By default, it will use your default email template. The template must be a
    * template using our built-in customizations or a custom HTML email for Passwords - Email Verification.
     */
    public ?string $verifyEmailTemplateId = null;

    public function __construct(
        string $organizationId,
        string $emailAddress,
        ?string $resetPasswordRedirectURL = null,
        ?int $resetPasswordExpirationMinutes = null,
        ?string $codeChallenge = null,
        ?string $loginRedirectURL = null,
        ?string $locale = null,
        ?string $resetPasswordTemplateId = null,
        ?string $verifyEmailTemplateId = null
    ) {
        $this->organizationId = $organizationId;
        $this->emailAddress = $emailAddress;
        $this->resetPasswordRedirectURL = $resetPasswordRedirectURL;
        $this->resetPasswordExpirationMinutes = $resetPasswordExpirationMinutes;
        $this->codeChallenge = $codeChallenge;
        $this->loginRedirectURL = $loginRedirectURL;
        $this->locale = $locale;
        $this->resetPasswordTemplateId = $resetPasswordTemplateId;
        $this->verifyEmailTemplateId = $verifyEmailTemplateId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['organization_id'],
            $data['email_address'],
            $data['reset_password_redirect_url'] ?? null,
            $data['reset_password_expiration_minutes'] ?? null,
            $data['code_challenge'] ?? null,
            $data['login_redirect_url'] ?? null,
            $data['locale'] ?? null,
            $data['reset_password_template_id'] ?? null,
            $data['verify_email_template_id'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'email_address' => $this->emailAddress,
            'reset_password_redirect_url' => $this->resetPasswordRedirectURL,
            'reset_password_expiration_minutes' => $this->resetPasswordExpirationMinutes,
            'code_challenge' => $this->codeChallenge,
            'login_redirect_url' => $this->loginRedirectURL,
            'locale' => $this->locale,
            'reset_password_template_id' => $this->resetPasswordTemplateId,
            'verify_email_template_id' => $this->verifyEmailTemplateId,
        ];
    }
}
