<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\WebAuthn;


final class AuthenticateStartRequest
{
    /** The domain for Passkeys or WebAuthn. Defaults to `window.location.hostname`. */
    public string $domain;
    /**
    * The `user_id` of an active user the Passkey or WebAuthn registration should be tied to. You may use an
    * `external_id` here if one is set for the user.
     */
    public ?string $userId = null;
    /**
    * If true, the `public_key_credential_creation_options` returned will be optimized for Passkeys with
    * `userVerification` set to `"preferred"`.
     */
    public ?bool $returnPasskeyCredentialOptions = null;

    public function __construct(
        string $domain,
        ?string $userId = null,
        ?bool $returnPasskeyCredentialOptions = null
    ) {
        $this->domain = $domain;
        $this->userId = $userId;
        $this->returnPasskeyCredentialOptions = $returnPasskeyCredentialOptions;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['domain'],
            $data['user_id'] ?? null,
            $data['return_passkey_credential_options'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'domain' => $this->domain,
            'user_id' => $this->userId,
            'return_passkey_credential_options' => $this->returnPasskeyCredentialOptions,
        ];
    }
}