<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\WebAuthn;

final class UpdateRequest
{
    /**
    * Globally unique UUID that identifies a Passkey or WebAuthn registration in the Stytch API. The
    * `webauthn_registration_id` is used when you need to operate on a specific User's WebAuthn registration.
     */
    public string $webauthnRegistrationId;
    /** The `name` of the WebAuthn registration or Passkey. */
    public string $name;

    public function __construct(
        string $webauthnRegistrationId,
        string $name
    ) {
        $this->webauthnRegistrationId = $webauthnRegistrationId;
        $this->name = $name;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['webauthn_registration_id'],
            $data['name']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'webauthn_registration_id' => $this->webauthnRegistrationId,
            'name' => $this->name,
        ];
    }
}
