<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\WebAuthn;


final class WebAuthnCredential
{
    /** The unique, public ID of the WebAuthn credential. */
    public string $credentialId;
    /** The unique ID for the Passkey or WebAuthn registration. */
    public string $webauthnRegistrationId;
    /** The type of the WebAuthn credential. Examples include `public-key`. */
    public string $type;
    /** The public key for the WebAuthn credential in base64 format. */
    public string $publicKey;

    public function __construct(
        string $credentialId,
        string $webauthnRegistrationId,
        string $type,
        string $publicKey
    ) {
        $this->credentialId = $credentialId;
        $this->webauthnRegistrationId = $webauthnRegistrationId;
        $this->type = $type;
        $this->publicKey = $publicKey;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['credential_id'],
            $data['webauthn_registration_id'],
            $data['type'],
            $data['public_key']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'credential_id' => $this->credentialId,
            'webauthn_registration_id' => $this->webauthnRegistrationId,
            'type' => $this->type,
            'public_key' => $this->publicKey,
        ];
    }
}