<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\M2M;

class M2MClient
{
    /** The ID of the client. */
    public string $clientId;
    /** A human-readable name for the client. */
    public string $clientName;
    /** A human-readable description for the client. */
    public string $clientDescription;
    /** The status of the client - either `active` or `inactive`. */
    public string $status;
    /** An array of scopes assigned to the client. */
    public array $scopes;
    /** The last four characters of the client secret. */
    public string $clientSecretLastFour;
    /** An arbitrary JSON object for storing application-specific data. */
    public ?array $trustedMetadata = null;
    /** The last four characters of the `next_client_secret`. Null if no `next_client_secret` exists. */
    public ?string $nextClientSecretLastFour = null;

    public function __construct(
        string $clientId,
        string $clientName,
        string $clientDescription,
        string $status,
        array $scopes,
        string $clientSecretLastFour,
        ?array $trustedMetadata = null,
        ?string $nextClientSecretLastFour = null
    ) {
        $this->clientId = $clientId;
        $this->clientName = $clientName;
        $this->clientDescription = $clientDescription;
        $this->status = $status;
        $this->scopes = $scopes;
        $this->clientSecretLastFour = $clientSecretLastFour;
        $this->trustedMetadata = $trustedMetadata;
        $this->nextClientSecretLastFour = $nextClientSecretLastFour;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['client_id'],
            $data['client_name'],
            $data['client_description'],
            $data['status'],
            $data['scopes'],
            $data['client_secret_last_four'],
            $data['trusted_metadata'] ?? null,
            $data['next_client_secret_last_four'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'client_id' => $this->clientId,
            'client_name' => $this->clientName,
            'client_description' => $this->clientDescription,
            'status' => $this->status,
            'scopes' => $this->scopes,
            'client_secret_last_four' => $this->clientSecretLastFour,
            'trusted_metadata' => $this->trustedMetadata,
            'next_client_secret_last_four' => $this->nextClientSecretLastFour,
        ];
    }
}
