<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\MagicLinks\Email;

final class LoginOrSignupResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /** Globally unique UUID that identifies a specific Member. */
    public string $memberId;
    /**
    * A flag indicating `true` if a new Member object was created and `false` if the Member object already
    * existed.
     */
    public bool $memberCreated;
    /** The [Member object](https://stytch.com/docs/b2b/api/member-object) */
    public \Stytch\B2B\Models\Organizations\Member $member;
    /** The [Organization object](https://stytch.com/docs/b2b/api/organization-object). */
    public \Stytch\B2B\Models\Organizations\Organization $organization;
    /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
     */
    public int $statusCode;

    public function __construct(
        string $requestId,
        string $memberId,
        bool $memberCreated,
        \Stytch\B2B\Models\Organizations\Member $member,
        \Stytch\B2B\Models\Organizations\Organization $organization,
        int $statusCode
    ) {
        $this->requestId = $requestId;
        $this->memberId = $memberId;
        $this->memberCreated = $memberCreated;
        $this->member = $member;
        $this->organization = $organization;
        $this->statusCode = $statusCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['member_id'],
            $data['member_created'],
            \Stytch\B2B\Models\Organizations\Member::fromArray($data['member']),
            \Stytch\B2B\Models\Organizations\Organization::fromArray($data['organization']),
            $data['status_code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'member_id' => $this->memberId,
            'member_created' => $this->memberCreated,
            'member' => $this->member,
            'organization' => $this->organization,
            'status_code' => $this->statusCode,
        ];
    }
}
