<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\TOTPs;

class RecoveryCodesResponse
{
    /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
     */
    public string $requestId;
    /** The unique ID of the affected User. */
    public string $userId;
    /**
    * An array containing a list of all TOTP instances (along with their recovery codes) for a given User in
    * the Stytch API.
     */
    public array $totps;
    /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
     */
    public int $statusCode;

    public function __construct(
        string $requestId,
        string $userId,
        array $totps,
        int $statusCode
    ) {
        $this->requestId = $requestId;
        $this->userId = $userId;
        $this->totps = $totps;
        $this->statusCode = $statusCode;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['user_id'],
            isset($data['totps']) ? array_map(fn ($item) => TOTP::fromArray($item), $data['totps']) : [],
            $data['status_code']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'user_id' => $this->userId,
            'totps' => $this->totps,
            'status_code' => $this->statusCode,
        ];
    }
}
