<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Users;


final class ExchangePrimaryFactorRequest
{
    /** The unique ID of a specific User. You may use an `external_id` here if one is set for the user. */
    public string $userId;
    /** The email address to exchange to. */
    public ?string $emailAddress = null;
    /** The phone number to exchange to. The phone number should be in E.164 format (i.e. +1XXXXXXXXXX). */
    public ?string $phoneNumber = null;

    public function __construct(
        string $userId,
        ?string $emailAddress = null,
        ?string $phoneNumber = null
    ) {
        $this->userId = $userId;
        $this->emailAddress = $emailAddress;
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['user_id'],
            $data['email_address'] ?? null,
            $data['phone_number'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'user_id' => $this->userId,
            'email_address' => $this->emailAddress,
            'phone_number' => $this->phoneNumber,
        ];
    }
}