<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Users;

final class ResultsMetadata
{
    /**
    * The total number of results returned by your search query. If totals have been disabled for your Stytch
    * Workspace to improve search performance, the value will always be -1.
     */
    public int $total;
    /**
    * The `next_cursor` string is returned when your search result contains more than one page of results.
    * This value is passed into your next search call in the `cursor` field.
     */
    public ?string $nextCursor = null;

    public function __construct(
        int $total,
        ?string $nextCursor = null
    ) {
        $this->total = $total;
        $this->nextCursor = $nextCursor;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['total'],
            $data['next_cursor'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'total' => $this->total,
            'next_cursor' => $this->nextCursor,
        ];
    }
}
