<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Users;

final class UserConnectedApp
{
    /** The ID of the Connected App. */
    public string $connectedAppId;
    /** The name of the Connected App. */
    public string $name;
    /** A description of the Connected App. */
    public string $description;
    /**
    * The type of Connected App. Supported values are `first_party`, `first_party_public`, `third_party`, and
    * `third_party_public`.
     */
    public string $clientType;
    /** The scopes granted to the Connected App at the completion of the last authorization flow. */
    public string $scopesGranted;
    /** The logo URL of the Connected App, if any. */
    public ?string $logoURL = null;

    public function __construct(
        string $connectedAppId,
        string $name,
        string $description,
        string $clientType,
        string $scopesGranted,
        ?string $logoURL = null
    ) {
        $this->connectedAppId = $connectedAppId;
        $this->name = $name;
        $this->description = $description;
        $this->clientType = $clientType;
        $this->scopesGranted = $scopesGranted;
        $this->logoURL = $logoURL;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['connected_app_id'],
            $data['name'],
            $data['description'],
            $data['client_type'],
            $data['scopes_granted'],
            $data['logo_url'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'connected_app_id' => $this->connectedAppId,
            'name' => $this->name,
            'description' => $this->description,
            'client_type' => $this->clientType,
            'scopes_granted' => $this->scopesGranted,
            'logo_url' => $this->logoURL,
        ];
    }
}
