<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\Consumer\Models\Fraud\Fingerprint;


final class LookupRequest
{
    /** The telemetry ID associated with the fingerprint getting looked up. */
    public string $telemetryId;
    /**
    * External identifiers that you wish to associate with the given telemetry ID. You will be able to search
    * for fingerprint results by these identifiers in the DFP analytics dashboard. External metadata fields
    * may not exceed 65 characters. They may only contain alphanumerics and the characters `_` `-` `+` `.` or
    * `@`.
     */
    public ?\Stytch\Consumer\Models\Fraud\Metadata $externalMetadata = null;

    public function __construct(
        string $telemetryId,
        ?\Stytch\Consumer\Models\Fraud\Metadata $externalMetadata = null
    ) {
        $this->telemetryId = $telemetryId;
        $this->externalMetadata = $externalMetadata;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['telemetry_id'],
            $data['external_metadata'] !== null ? \Stytch\Consumer\Models\Fraud\Metadata::fromArray($data['external_metadata']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'telemetry_id' => $this->telemetryId,
            'external_metadata' => $this->externalMetadata,
        ];
    }
}