<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\SSO;

final class DeleteConnectionRequest
{
    /**
    * The organization ID that the SSO connection belongs to. You may also use the organization_slug or
    * organization_external_id here as a convenience.
     */
    public string $organizationId;
    /** The ID of the SSO connection. SAML, OIDC, and External connection IDs can be provided. */
    public string $connectionId;

    public function __construct(
        string $organizationId,
        string $connectionId
    ) {
        $this->organizationId = $organizationId;
        $this->connectionId = $connectionId;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['organization_id'],
            $data['connection_id']
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'connection_id' => $this->connectionId,
        ];
    }
}
