<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\SSO;

final class EncryptionPrivateKey
{
    public string $privateKeyId;
    public string $privateKey;
    public ?string $createdAt = null;

    public function __construct(
        string $privateKeyId,
        string $privateKey,
        ?string $createdAt = null
    ) {
        $this->privateKeyId = $privateKeyId;
        $this->privateKey = $privateKey;
        $this->createdAt = $createdAt;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['private_key_id'],
            $data['private_key'],
            $data['created_at'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'private_key_id' => $this->privateKeyId,
            'private_key' => $this->privateKey,
            'created_at' => $this->createdAt,
        ];
    }
}
