<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\SSO;

final class SAMLConnection
{
    /**
    * Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to
    * perform operations on an Organization, so be sure to preserve this value. You may also use the
    * organization_slug or organization_external_id here as a convenience.
     */
    public string $organizationId;
    /** Globally unique UUID that identifies a specific SAML Connection. */
    public string $connectionId;
    /**
    * The status of the connection. The possible values are pending or active. See the
    * [Update SAML Connection endpoint](https://stytch.com/docs/b2b/api/update-saml-connection) for more
    * details.
     */
    public string $status;
    /** A globally unique name for the IdP. This will be provided by the IdP. */
    public string $idpEntityId;
    /** A human-readable display name for the connection. */
    public string $displayName;
    /** The URL for which assertions for login requests will be sent. This will be provided by the IdP. */
    public string $idpSSOURL;
    /**
    * The URL of the Assertion Consumer Service. This value will be passed to the IdP to redirect the Member
    * back to Stytch after a sign-in attempt. Read our
    * [SAML Overview](https://stytch.com/docs/b2b/api/saml-overview) for more info.
     */
    public string $acsURL;
    /**
    * The URL of the Audience Restriction. This value will indicate that Stytch is the intended audience of an
    * assertion. Read our [SAML Overview](https://stytch.com/docs/b2b/api/saml-overview) for more info.
     */
    public string $audienceUri;
    /**
    * A list of X.509 certificates Stytch will use to sign its assertion requests. Certificates should be
    * uploaded to the IdP.
     */
    public array $signingCertificates;
    /**
    * A list of X.509 certificates Stytch will use to validate an assertion callback. Certificates should be
    * populated from the IdP.
     */
    public array $verificationCertificates;
    public array $encryptionPrivateKeys;
    /**
    * All Members who log in with this SAML connection will implicitly receive the specified Roles. See the
    * [RBAC guide](https://stytch.com/docs/b2b/guides/rbac/role-assignment) for more information about role
    * assignment.
     */
    public array $samlConnectionImplicitRoleAssignments;
    /**
    * Defines the names of the SAML groups
    *  that grant specific role assignments. For each group-Role pair, if a Member logs in with this SAML
    * connection and
    *  belongs to the specified SAML group, they will be granted the associated Role. See the
    *  [RBAC guide](https://stytch.com/docs/b2b/guides/rbac/role-assignment) for more information about role
    * assignment.
     */
    public array $samlGroupImplicitRoleAssignments;
    /**
    * An alternative URL to use for the Audience Restriction. This value can be used when you wish to migrate
    * an existing SAML integration to Stytch with zero downtime. Read our
    * [SSO migration guide](https://stytch.com/docs/b2b/guides/migrations/additional-migration-considerations)
    * for more info.
     */
    public string $alternativeAudienceUri;
    /**
    * Name of the IdP. Enum with possible values: `classlink`, `cyberark`, `duo`, `google-workspace`,
    * `jumpcloud`, `keycloak`, `miniorange`, `microsoft-entra`, `okta`, `onelogin`, `pingfederate`,
    * `rippling`, `salesforce`, `shibboleth`, or `generic`.
    *
    * Specifying a known provider allows Stytch to handle any provider-specific logic.
     */
    public string $identityProvider;
    /**
    * The NameID format the SAML Connection expects to use. Defaults to
    * `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`.
     */
    public string $nameidFormat;
    /**
    * An alternative URL to use for the `AssertionConsumerServiceURL` in SP initiated SAML AuthNRequests. This
    * value can be used when you wish to migrate an existing SAML integration to Stytch with zero downtime.
    * Note that you will be responsible for proxying requests sent to the Alternative ACS URL to Stytch. Read
    * our
    * [SSO migration guide](https://stytch.com/docs/b2b/guides/migrations/additional-migration-considerations)
    * for more info.
     */
    public string $alternativeAcsURL;
    /**
    * Determines whether IDP initiated auth is allowed for a given SAML connection. Defaults to false (IDP
    * Initiated Auth is enabled).
     */
    public bool $idpInitiatedAuthDisabled;
    public bool $allowGatewayCallback;
    /**
    * An object that represents the attributes used to identify a Member. This object will map the IdP-defined
    * User attributes to Stytch-specific values. Required attributes: `email` and one of `full_name` or
    * `first_name` and `last_name`.
     */
    public ?array $attributeMapping = null;

    public function __construct(
        string $organizationId,
        string $connectionId,
        string $status,
        string $idpEntityId,
        string $displayName,
        string $idpSSOURL,
        string $acsURL,
        string $audienceUri,
        array $signingCertificates,
        array $verificationCertificates,
        array $encryptionPrivateKeys,
        array $samlConnectionImplicitRoleAssignments,
        array $samlGroupImplicitRoleAssignments,
        string $alternativeAudienceUri,
        string $identityProvider,
        string $nameidFormat,
        string $alternativeAcsURL,
        bool $idpInitiatedAuthDisabled,
        bool $allowGatewayCallback,
        ?array $attributeMapping = null
    ) {
        $this->organizationId = $organizationId;
        $this->connectionId = $connectionId;
        $this->status = $status;
        $this->idpEntityId = $idpEntityId;
        $this->displayName = $displayName;
        $this->idpSSOURL = $idpSSOURL;
        $this->acsURL = $acsURL;
        $this->audienceUri = $audienceUri;
        $this->signingCertificates = $signingCertificates;
        $this->verificationCertificates = $verificationCertificates;
        $this->encryptionPrivateKeys = $encryptionPrivateKeys;
        $this->samlConnectionImplicitRoleAssignments = $samlConnectionImplicitRoleAssignments;
        $this->samlGroupImplicitRoleAssignments = $samlGroupImplicitRoleAssignments;
        $this->alternativeAudienceUri = $alternativeAudienceUri;
        $this->identityProvider = $identityProvider;
        $this->nameidFormat = $nameidFormat;
        $this->alternativeAcsURL = $alternativeAcsURL;
        $this->idpInitiatedAuthDisabled = $idpInitiatedAuthDisabled;
        $this->allowGatewayCallback = $allowGatewayCallback;
        $this->attributeMapping = $attributeMapping;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['organization_id'],
            $data['connection_id'],
            $data['status'],
            $data['idp_entity_id'],
            $data['display_name'],
            $data['idp_sso_url'],
            $data['acs_url'],
            $data['audience_uri'],
            isset($data['signing_certificates']) ? array_map(fn($item) => X509Certificate::fromArray($item), $data['signing_certificates']) : [],
            isset($data['verification_certificates']) ? array_map(fn($item) => X509Certificate::fromArray($item), $data['verification_certificates']) : [],
            isset($data['encryption_private_keys']) ? array_map(fn($item) => EncryptionPrivateKey::fromArray($item), $data['encryption_private_keys']) : [],
            isset($data['saml_connection_implicit_role_assignments']) ? array_map(fn($item) => SAMLConnectionImplicitRoleAssignment::fromArray($item), $data['saml_connection_implicit_role_assignments']) : [],
            isset($data['saml_group_implicit_role_assignments']) ? array_map(fn($item) => SAMLGroupImplicitRoleAssignment::fromArray($item), $data['saml_group_implicit_role_assignments']) : [],
            $data['alternative_audience_uri'],
            $data['identity_provider'],
            $data['nameid_format'],
            $data['alternative_acs_url'],
            $data['idp_initiated_auth_disabled'],
            $data['allow_gateway_callback'],
            $data['attribute_mapping'] ?? null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'connection_id' => $this->connectionId,
            'status' => $this->status,
            'idp_entity_id' => $this->idpEntityId,
            'display_name' => $this->displayName,
            'idp_sso_url' => $this->idpSSOURL,
            'acs_url' => $this->acsURL,
            'audience_uri' => $this->audienceUri,
            'signing_certificates' => $this->signingCertificates,
            'verification_certificates' => $this->verificationCertificates,
            'encryption_private_keys' => $this->encryptionPrivateKeys,
            'saml_connection_implicit_role_assignments' => $this->samlConnectionImplicitRoleAssignments,
            'saml_group_implicit_role_assignments' => $this->samlGroupImplicitRoleAssignments,
            'alternative_audience_uri' => $this->alternativeAudienceUri,
            'identity_provider' => $this->identityProvider,
            'nameid_format' => $this->nameidFormat,
            'alternative_acs_url' => $this->alternativeAcsURL,
            'idp_initiated_auth_disabled' => $this->idpInitiatedAuthDisabled,
            'allow_gateway_callback' => $this->allowGatewayCallback,
            'attribute_mapping' => $this->attributeMapping,
        ];
    }
}
