<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\Discovery;


final class Membership
{
    /**
    * Either `active_member`, `pending_member`, `invited_member`, `eligible_to_join_by_email_domain`, or
    * `eligible_to_join_by_oauth_tenant`
     */
    public string $type;
    /** An object containing additional metadata about the membership, if available. */
    public ?array $details = null;
    /**
    * The [Member object](https://stytch.com/docs/b2b/api/member-object) if one already exists, or null if one
    * does not.
     */
    public ?\Stytch\B2B\Models\Organizations\Member $member = null;

    public function __construct(
        string $type,
        ?array $details = null,
        ?\Stytch\B2B\Models\Organizations\Member $member = null
    ) {
        $this->type = $type;
        $this->details = $details;
        $this->member = $member;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['type'],
            $data['details'] ?? null,
            $data['member'] !== null ? \Stytch\B2B\Models\Organizations\Member::fromArray($data['member']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'type' => $this->type,
            'details' => $this->details,
            'member' => $this->member,
        ];
    }
}