<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Api;

use Stytch\Core\Client;

class OTPs
{
    private Client $client;

    public OTPsSms $sms;
    public OTPsEmail $email;

    public function __construct(Client $client)
    {
        $this->client = $client;

        $this->sms = new OTPsSms($this->client);
        $this->email = new OTPsEmail($this->client);
    }

}
