<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\RBAC\Organizations;

final class SetOrgPolicyRequest
{
    public string $organizationId;
    public ?\Stytch\B2B\Models\RBAC\OrgPolicy $orgPolicy = null;

    public function __construct(
        string $organizationId,
        ?\Stytch\B2B\Models\RBAC\OrgPolicy $orgPolicy = null
    ) {
        $this->organizationId = $organizationId;
        $this->orgPolicy = $orgPolicy;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['organization_id'],
            isset($data['org_policy']) && $data['org_policy'] !== null ? \Stytch\B2B\Models\RBAC\OrgPolicy::fromArray($data['org_policy']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'organization_id' => $this->organizationId,
            'org_policy' => $this->orgPolicy,
        ];
    }
}
