<?php

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

namespace Stytch\B2B\Models\RBAC\Organizations;

final class SetOrgPolicyResponse
{
    public string $requestId;
    public int $statusCode;
    public ?\Stytch\B2B\Models\RBAC\OrgPolicy $orgPolicy = null;

    public function __construct(
        string $requestId,
        int $statusCode,
        ?\Stytch\B2B\Models\RBAC\OrgPolicy $orgPolicy = null
    ) {
        $this->requestId = $requestId;
        $this->statusCode = $statusCode;
        $this->orgPolicy = $orgPolicy;
    }

    /**
     * Create an instance from an array
     *
     * @param array $data
     * @return static
     */
    public static function fromArray(array $data): static
    {
        return new static(
            $data['request_id'],
            $data['status_code'],
            isset($data['org_policy']) && $data['org_policy'] !== null ? \Stytch\B2B\Models\RBAC\OrgPolicy::fromArray($data['org_policy']) : null
        );
    }

    /**
     * Convert to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'request_id' => $this->requestId,
            'status_code' => $this->statusCode,
            'org_policy' => $this->orgPolicy,
        ];
    }
}
