name: Publish stytch Packagist package

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish stytch package to Packagist
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.1-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Run tests
        run: |
          composer install --prefer-dist --no-progress
          vendor/bin/phpunit

      - name: Get version from tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "release_tag=$VERSION" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for composer.json version change
        id: diff
        run: |
          FOUND=0
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == "composer.json" ]]; then
              FOUND=1
            fi
          done
          echo "diff=$FOUND" >> $GITHUB_OUTPUT

      - name: Trigger Packagist update
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        if: (steps.version.outputs.is_tag == 'true' || steps.diff.outputs.diff != 0) && env.PACKAGIST_TOKEN != ''
        run: |
          curl -XPOST -H'content-type:application/json' \
            'https://packagist.org/api/update-package?username=stytch&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
            -d'{"repository":{"url":"https://github.com/stytch/stytch-php"}}'

      - name: Create release
        if: steps.version.outputs.is_tag == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ steps.version.outputs.release_tag }}" --generate-notes